import type { Apparatus, ApparatusSpec } from "@/lib/opening/types";
import { CIRCUITMIND_LINE, MIRRORFI_VAULT, RISK_ENGINE, LEADS_HALL, VERIDIAN_PLANT, VERIDIAN_STILL, VERIDIAN_EXCHANGE } from "@/content/project-figures";
import { METRICS, POSITIONING, RETRIEVAL_SPLIT } from "@/lib/metrics";

export function repoArtifacts(github: string, name?: string): { label: string; href: string }[] {
  if (!github) return [];
  return [{ label: name ? `View ${name} source` : "GitHub repository", href: github }];
}

export const resumeData = {
  name: "Anas Tarek Qumhiyeh",
  tagline: POSITIONING.tagline,
  headline: POSITIONING.dek,
  targetRoles: "software engineering roles in fintech, ML infrastructure, and data platforms.",
  graduateNote: POSITIONING.graduateNote,
  email: "anasqumhiyeh@gmail.com",
  linkedin: "linkedin.com/in/anasqumhiyeh/",
  github: "github.com/Mizore66",
  education: {
    school: "Monash University",
    location: "Bandar Sunway, Selangor, Malaysia",
    degree: "Bachelor of Engineering (Honours), Specialisation in Software Engineering",
    honours: "First Class Honours",
    graduation: "May 2026",
    wam: "82.1",
    cgpa: "3.82",
  },
  skills: {
    languages: ["Java", "Python", "C/C++", "JavaScript", "TypeScript", "HTML/CSS", "MATLAB", "Flutter", "C#", "PHP", "Scala"],
    frameworks: ["React", "Node.js", "Flask", "jQuery", "Next.js", "ASP.NET", "Laravel", "NestJS"],
    devTools: ["Git", "GitLab CI/CD", "Postman", "Swagger", "Grafana", "Loki", "Docker", "Kubernetes", "AWS", "ArgoCD"],
    libraries: ["pandas", "NumPy", "Matplotlib", "PyTorch", "TensorFlow", "NLTK", "spaCy", "FastAPI", "Kafka"],
    databases: ["MySQL", "Oracle Database", "MongoDB", "Firebase", "PostgreSQL", "Neo4j"],
  },
  skillsCore: {
    languages: ["Python", "TypeScript", "Java", "C/C++"],
    infrastructure: ["Docker", "Kubernetes", "PostgreSQL", "Neo4j", "Kafka", "AWS", "FastAPI"],
    ml: ["PyTorch", "LangGraph", "PySpark"],
  },
  experience: [
    {
      title: "Full-stack AI Engineer",
      type: "Contract",
      company: "Monash University",
      period: "Nov 2025 – Feb 2026",
      tech: ["LangGraph", "Neo4j", "FastAPI"],
      bullets: [
        `${METRICS.monashRetrieval.impact} — self-correcting Text-to-Cypher over a Neo4j graph of ${METRICS.monashRetrieval.corpus}.`,
        "Hybrid retrieval: embeddings plus multi-hop graph walks for prerequisites and credit-transfer.",
        `A graph-logic SLM distilled from that reasoning: ${METRICS.slmLatency.display}, contradictions surfaced for administrators.`,
      ],
      impact: METRICS.monashRetrieval.impact,
    },
    {
      title: "Full-stack Engineer",
      type: "Contract Employee",
      company: "Western Digital",
      period: "Feb 2025 – Dec 2025",
      tech: ["Next.js", "ASP.NET", "PostgreSQL", "Docker"],
      bullets: [
        `${METRICS.wdOversight.display} — lab dashboard with role-based access for 50+ staff.`,
        "CRUD and analytics behind those roles.",
        "WebSocket to the lab's deep-learning model; shortest path between stations in under 100 ms on that dashboard path.",
      ],
      impact: METRICS.wdOversight.display,
    },
    {
      title: "Software Engineer Intern",
      type: "Intern",
      company: "Setel",
      period: "Jul 2025 – Dec 2025",
      tech: ["Docker", "Kubernetes", "MERN Stack", "Swagger", "NestJS"],
      bullets: [
        "Authorization and capture of stored payment methods on the payment engine.",
        "Checkout and capture documented so a new developer could follow the path without a walkthrough.",
        `${METRICS.setelCoverage.display} on checkout and capture.`,
        `${METRICS.setelDefects.display} on that path (separate observation, not claimed as the coverage's effect).`,
      ],
      impact: METRICS.setelDefects.display,
    },
    {
      title: "Project Engineer Intern",
      type: "Intern",
      company: "Petronas",
      period: "Nov 2024 – Feb 2025",
      tech: ["MATLAB", "Python", "MathCAD"],
      bullets: [
        "Converted the department's MATLAB back-end to Python, replacing paid licences with free packages.",
        "Wrote user test cases for features after they reached production.",
        "Presented usability findings to department leadership.",
      ],
      impact: "Migrated MATLAB back-end to Python, replacing paid licences",
    },
  ],
  projects: [
    {
      name: "Veridian",
      slug: "veridian",
      subtitle: "MLOps Tradeoff Engine",
      purpose: "Intercepts Terraform and Kubernetes and recommends a lower-carbon compute configuration before the spike.",
      date: "Apr 2026",
      tech: ["Python", "Terraform", "BigQuery", "GCP Vertex AI", "GitLab Duo", "MCP"],
      bullets: [
        "GitLab Duo plus Model Context Protocol (MCP) intercept Terraform and Kubernetes as they change.",
        "Vertex AI recommends a quantized, lower-carbon compute configuration for the model on the desk.",
        "BigQuery holds the ESG ledger; it is not on the request.",
      ],
      impact: "Automatic lower-carbon infrastructure recommendation",
      why: "The box named after the spike is already the wrong box. Model Context Protocol (MCP) here means the Terraform change is read as it is written, before that box is already running.",
      constraint: "The ledger had to stay off the request path so a slow or missing carbon number could not stall a provision.",
      limitation: "Private project archive. 99.9% uptime and −15% emissions are Cloud Run evaluations; evaluation period, sample size, and the emissions calculation source were not filed — not a named production SLO.",
      example: "Input: a Terraform intent. Output: the named box, with the carbon ledger written beside the request, not on it.",
      evidenceNote: METRICS.veridianUptime.note,
      evidenceKind: METRICS.veridianUptime.kind,
      github: "",
      plate: "/plates/plate-veridian.jpg",
      plateCaption: "Veridian intercepts the change — halftone plate, illustrative.",
      plateAlt: "Halftone photograph: an engineer at a drafting table, an infrastructure drawing unrolled before him.",
      description:
        "GitLab Duo intercepts the Terraform change; a Model Context Protocol (MCP) server on Cloud Run asks Vertex what the model needs; BigQuery keeps the carbon ledger off that request.",
      judgment: "Read the Terraform as it is written. Vertex recommends a lower-carbon compute configuration. The carbon ledger stays off the request path.",
      meta: "GitLab Duo intercepts Terraform; Vertex recommends a lower-carbon compute configuration; BigQuery keeps the carbon ledger off the request.",
      patent: VERIDIAN_PLANT satisfies ApparatusSpec,
      apparatus: {
        name: "Veridian",
        runtime: "Cloud Run",
        path: [
          { name: "GitLab Duo + MCP", role: "intercepts Terraform / K8s" },
          { name: "Vertex AI", role: "profile the model" },
        ],
        beside: [
          { name: "BigQuery", role: "ESG ledger — not this request" },
          { name: "Python", role: "glue, not a hop" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "CircuitMindAI",
      slug: "circuitmindai",
      subtitle: "PCB Inspection",
      purpose: "Detects PCB faults from images and returns voice-guided inspection steps, with cached results for network loss.",
      date: "Mar 2026",
      tech: ["Next.js", "AWS Bedrock", "Express", "Amazon OSS", "GitHub Actions"],
      bullets: [
        "Nova Pro reads the copper; Nova Sonic talks the operator through the fault.",
        "Next.js and Express on ECS Fargate, with GitHub Actions stamping ECR.",
        "Edge cache holds the inspection when the network drops.",
        "A REST API for the line, not a slogan about performance.",
      ],
      impact: "PCB fault detection",
      why: "An operator inspecting a board needs to see the copper fault and hear the work, including when the network drops. A detector that only lives on a server is a detector the floor cannot use.",
      inspectNote: "Express API (backend-js/) and Next.js UI (frontend/).",
      example: "Input: a board image and operator audio. Output: a fault overlay on the copper, with the work still audible when the network drops.",
      github: "https://github.com/Mizore66/CircuitMindAI",
      plate: "/plates/plate-circuitmind.jpg",
      plateCaption: "CircuitMindAI under the loupe — halftone plate, illustrative.",
      plateAlt: "Halftone photograph: a printed circuit board under a loupe, traces filling the frame.",
      description:
        "CircuitMindAI inspects circuit boards: Nova Pro reads the copper, Nova Sonic talks the operator through the fault. Next.js and Express sit on ECS Fargate; GitHub Actions stamps the image.",
      judgment: "Vision on the copper and voice for the operator, with the inspection cached at the edge so the floor can keep working when the network drops.",
      constraint: "The inspection has to survive a dropped network. There is no live host after the exhibit.",
      limitation: "No live host. The argument is this exhibit and the public repository. Detection quality (precision, latency, confusion) was not filed.",
      meta: "Nova Pro reads the copper; Nova Sonic talks the operator through the fault. Next.js and Express on ECS Fargate.",
      patent: CIRCUITMIND_LINE satisfies ApparatusSpec,
      apparatus: {
        name: "CircuitMindAI",
        runtime: "ECS Fargate",
        path: [
          { name: "Next.js", role: "UI" },
          { name: "Express", role: "API" },
        ],
        forks: [
          { name: "Bedrock Nova", role: "vision + voice" },
          { name: "OpenSearch", role: "index" },
        ],
        beside: [{ name: "GitHub Actions", role: "CI/CD to ECR" }],
      } satisfies Apparatus,
    },
    {
      name: "MirrorFi",
      slug: "mirrorfi",
      subtitle: "Solana Vault Strategy Platform",
      purpose: "Builds, shares, and executes no-code Solana vault strategies across Drift, Jupiter, and Meteora.",
      date: "May 2025",
      tech: ["Next.js", "Node.js", "MongoDB", "Solana", "ShadCN"],
      bullets: [
        "Grand Prize, Solana Megahack 2025 — builds, shares, and executes no-code vault strategies. Prize clipping; source is the public repository.",
        "Drift, Jupiter, and Meteora in one schematic.",
        "MongoDB stores the copy so another desk can run it.",
        "A governor rebalances the pool when APY moves.",
      ],
      impact: "Grand Prize Winner",
      contextLabel: "Grand Prize, Solana Megahack 2025",
      inspectNote: "Source is the public Megahack repository.",
      github: "https://github.com/Mizore66/MirrorFi",
      plate: "/plates/plate-mirrorfi.jpg",
      plateCaption: "MirrorFi at the vault wall — halftone plate, illustrative.",
      plateAlt: "Halftone photograph: a vault door and lock-work, lit like a bank interior.",
      description:
        "A Next.js desk draws the vault line; Node.js talks to Drift, Jupiter, and Meteora; MongoDB stores the copy so another desk can run it.",
      why: "Two vault desks, two chains, and a hand-off that lived in a document. The failure is the gap between the schematic and the desk that has to fire it.",
      judgment: "One schematic that draws, shares, and fires — so the hand-off is the same object the operator sees.",
      constraint: "A Megahack weekend: one schematic had to ship, without a live host after the prize.",
      limitation: "No live host. Source is the public Megahack repository.",
      example: "Input: a vault line on the schematic. Output: the same object shared and fired at Drift, Jupiter, or Meteora.",
      meta: "Builds, shares, and executes no-code Solana vault strategies across Drift, Jupiter, and Meteora. Grand Prize, Megahack 2025; source is the public repository.",
      patent: MIRRORFI_VAULT satisfies ApparatusSpec,
      apparatus: {
        name: "MirrorFi",
        path: [
          { name: "Next.js", role: "no-code UI" },
          { name: "Node.js", role: "API" },
        ],
        forks: [
          { name: "MongoDB", role: "shareable strategies" },
          { name: "Solana", role: "Drift · Jupiter · Meteora" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "Multi-Agent GraphRAG",
      slug: "multi-agent-graphrag",
      subtitle: "Policy-corpus retrieval",
      purpose: "LangGraph over an independent university handbook and policy archive, with a vector fallback.",
      date: "Oct 2025",
      tech: ["LangGraph", "Neo4j", "Vector DB", "Knowledge Graphs", "RAG"],
      bullets: [
        `${METRICS.graphragRetrieval.impact} as filed (not Recall@k) — ${METRICS.graphragRetrieval.method}.`,
        "Cypher written by the agent, then checked, on that independent handbook and policy archive.",
        "Global-to-local retrieval when the question spans the handbook.",
        "Ambiguous questions fall back to a broader semantic search.",
      ],
      impact: METRICS.graphragRetrieval.impact,
      evidenceNote: METRICS.graphragRetrieval.note,
      evidenceKind: METRICS.graphragRetrieval.kind,
      github: "",
      plate: "/plates/plate-graphrag.jpg",
      plateCaption: "GraphRAG at the card catalog — halftone plate, illustrative.",
      plateAlt: "Halftone photograph: wooden card-catalog drawers, one drawer open on a labelled card.",
      description:
        "LangGraph asks Neo4j for an independent university handbook and policy archive, then a vector store when the graph is silent. Agents write Cypher, check it, and try again.",
      judgment:
        "The graph is the structured path for prerequisites and policy; the vector store is the fallback when the graph is silent.",
      why: "A question about prerequisites has to walk the graph, not only the nearest paragraph. This archive is not the Monash regulations corpus.",
      constraint: "Prerequisites and credit-transfer are edges, not another embedding dump.",
      limitation: "Ambiguous questions fall back to a broader semantic search. Sample size and Recall@k were not filed.",
      split: RETRIEVAL_SPLIT,
      example: "Input: a policy question. Output: a neighbourhood of clauses from the independent handbook archive, not a vector-only nearest neighbour.",
      meta: `LangGraph over an independent university handbook and policy archive: agents write Cypher, check it, and fall back to a vector store. ${METRICS.graphragRetrieval.strip}.`,
      patent: VERIDIAN_EXCHANGE satisfies ApparatusSpec,
      apparatus: {
        name: "Multi-Agent GraphRAG",
        path: [{ name: "LangGraph", role: "orchestrator" }],
        forks: [
          { name: "Neo4j", role: "structured" },
          { name: "Vector DB", role: "unstructured" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "Financial Risk Predictor",
      slug: "financial-risk-predictor",
      subtitle: "ML Risk Assessment",
      purpose: "Daily credit-risk scores that have to be interpreted, served, and retrained.",
      date: "Jul 2025",
      tech: ["TensorFlow", "XGBoost", "LightGBM", "BentoML", "SHAP"],
      bullets: [
        `${METRICS.riskAuc.display} on that sample. A 15% lift was noted against an unnamed baseline — that comparison is not independently interpretable.`,
        "SHAP names the drivers on the score.",
        "Daily retrain from Kafka so the score is this morning's tape.",
      ],
      impact: "0.87 AUC-ROC score",
      evidenceNote: METRICS.riskAuc.note,
      evidenceKind: METRICS.riskAuc.kind,
      why: "Daily credit scores that a desk has to interpret, serve, and retrain — not a notebook that dies after the plot.",
      judgment: "LightGBM and XGBoost with SHAP, served through BentoML, with Kafka carrying the stream so the model can be retrained without taking the API down.",
      limitation: "The 15% lift names an unnamed baseline. A −30% inference latency on the BentoML hatch was also noted; hardware and percentile were not filed.",
      example: "Input: the morning tape on Kafka. Output: a score with SHAP drivers, served through BentoML.",
      github: "",
      plate: "/plates/plate-risk.jpg",
      plateCaption: "Financial Risk Predictor — the ledger, halftone plate, illustrative.",
      plateAlt: "Halftone photograph: an open ledger with ruled columns, a pen resting on the page.",
      description:
        "Kafka feeds the daily tape; LightGBM and XGBoost score it; SHAP writes why; BentoML serves the number.",
      meta: "Kafka feeds the daily tape. LightGBM and XGBoost score it at 0.87 AUC. SHAP writes why. BentoML serves the number.",
      patent: RISK_ENGINE satisfies ApparatusSpec,
      apparatus: {
        name: "Financial Risk Predictor",
        path: [
          { name: "Kafka", role: "daily retrain" },
          { name: "LightGBM / XGBoost", role: "0.87 AUC" },
          { name: "BentoML", role: "serving API" },
        ],
        beside: [{ name: "SHAP", role: "why the score" }],
      } satisfies Apparatus,
    },
    {
      name: "Distributed Lead Scorer",
      slug: "distributed-lead-scorer",
      subtitle: "Large-Scale Data Mining Pipeline",
      purpose: "Scores conversion on a hundred million events a day, with checkpoints so a failed hour can resume.",
      date: "May 2025",
      tech: ["PyTorch DDP", "PySpark", "Deep Interest Network", "Distributed Computing"],
      bullets: [
        `${METRICS.leadThroughput.display} on PySpark; hours of latency cut to minutes. Pipeline capacity, not sustained traffic.`,
        "Deep Interest Network on PyTorch DDP across the GPU cluster.",
        "Automated evaluation so a bad net does not ship.",
        "Checkpoints resume a failed hour from the last written slice.",
      ],
      impact: METRICS.leadThroughput.display,
      evidenceNote: METRICS.leadThroughput.note,
      evidenceKind: METRICS.leadThroughput.kind,
      why: "A conversion score that takes hours is a score the desk cannot use on today's tape.",
      judgment: "PySpark for the feature path; a Deep Interest Network on PyTorch DDP for the score; checkpoints so a dead job resumes from the last written slice.",
      constraint: "A failed hour had to resume from the last good slice. The 100 million events per day figure is pipeline capacity, not sustained traffic.",
      limitation: "Capacity benchmark. Cluster size, input distribution, and runtime were not filed.",
      example: "Input: an event stream sized at 100 million events per day. Output: conversion scores, with a failed hour resumed from the last written slice.",
      github: "",
      plate: "/plates/plate-leads.jpg",
      plateCaption: "Distributed Lead Scorer — the sorting hall, halftone plate, illustrative.",
      plateAlt: "Halftone photograph: a mail-sorting hall, pigeonholes stretching into the distance.",
      description:
        "PySpark sorts 100M events/day into features; a Deep Interest Network on PyTorch DDP scores conversion; checkpoints resume a failed hour from the last written slice.",
      meta: "PySpark sorts 100M events a day. A Deep Interest Network on PyTorch DDP scores conversion. Checkpoints resume a failed hour from the last written slice.",
      patent: LEADS_HALL satisfies ApparatusSpec,
      apparatus: {
        name: "Distributed Lead Scorer",
        path: [
          { name: "PySpark", role: "100M+ events / day" },
          { name: "PyTorch DDP", role: "Deep Interest Network" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "SLM Distillation Engine",
      slug: "slm-distillation-engine",
      subtitle: "Knowledge Distillation & Fine-Tuning",
      purpose: "A 70B teacher compressed into a 3B student that keeps the same job.",
      date: "Jul 2025",
      tech: ["PyTorch", "QLoRA", "DeepSpeed", "FlashAttention"],
      bullets: [
        `${METRICS.slmInference.display} — 70B teacher into a 3B student. Tokens/second, hardware, and batch size were not filed.`,
        "QLoRA on the domain set.",
        "DeepSpeed and FlashAttention on the compression path.",
      ],
      impact: METRICS.slmInference.impact,
      why: "I used QLoRA to distil traces from a 70B teacher into a deployable 3B student.",
      constraint: "The student had to keep the same job on a smaller piece. A named evaluation for quality parity was not filed.",
      limitation: "12x inference is an evaluation on the 70B to 3B path, not a production serving number. −40% memory and 98% pass were also noted; hardware, batch size, and the named evaluation were not filed.",
      example: "Input: traces from a 70B teacher. Output: a 3B student on the same job. Tokens/second were not filed.",
      evidenceNote: METRICS.slmInference.note,
      evidenceKind: METRICS.slmInference.kind,
      github: "",
      plate: "/plates/plate-slm.jpg",
      plateCaption: "SLM Distillation — teacher and student machines, halftone plate, illustrative.",
      plateAlt: "Halftone photograph: two machines side by side, the smaller one cabled to the larger.",
      description:
        "A 70B teacher writes the traces; QLoRA, DeepSpeed and FlashAttention compress them into a 3B student that keeps the same job.",
      meta: "A 70B teacher writes the traces; QLoRA, DeepSpeed and FlashAttention compress them into a 3B student. 12× inference.",
      patent: VERIDIAN_STILL satisfies ApparatusSpec,
      apparatus: {
        name: "SLM Distillation Engine",
        runtime: "DeepSpeed",
        path: [
          { name: "70B teacher", role: "source" },
          { name: "QLoRA", role: "distill" },
          { name: "3B SLM", role: "12× inference" },
        ],
        beside: [{ name: "FlashAttention", role: "memory" }],
      } satisfies Apparatus,
    },
  ],
};
