import type { Apparatus, ApparatusSpec } from "@/lib/opening/types";
import { CIRCUITMIND_LINE, MIRRORFI_VAULT, RISK_ENGINE, LEADS_HALL, VERIDIAN_PLANT, VERIDIAN_STILL, VERIDIAN_EXCHANGE } from "@/content/project-figures";
import { METRICS, POSITIONING, RETRIEVAL_SPLIT } from "@/lib/metrics";

export function repoArtifacts(github: string, name?: string): { label: string; href: string }[] {
  if (!github) return [];
  return [{ label: name ? `View ${name} source` : "GitHub repository", href: github }];
}

export const resumeData = {
  name: "Anas Tarek Qumhiyeh",
  tagline: POSITIONING.tagline,
  headline: POSITIONING.dek,
  targetRoles: "early-career software engineering roles in fintech or AI infrastructure.",
  graduateNote: POSITIONING.graduateNote,
  email: "anasqumhiyeh@gmail.com",
  linkedin: "linkedin.com/in/anasqumhiyeh/",
  github: "github.com/Mizore66",
  education: {
    school: "Monash University",
    location: "Bandar Sunway, Selangor, Malaysia",
    degree: "Bachelor of Engineering (Honours), Specialisation in Software Engineering",
    honours: "First Class Honours",
    graduation: "May 2026",
    wam: "82.1",
    cgpa: "3.82",
  },
  skills: {
    languages: ["Java", "Python", "C/C++", "JavaScript", "TypeScript", "HTML/CSS", "MATLAB", "Flutter", "C#", "PHP", "Scala"],
    frameworks: ["React", "Node.js", "Flask", "jQuery", "Next.js", "ASP.NET", "Laravel", "NestJS"],
    devTools: ["Git", "GitLab CI/CD", "Postman", "Swagger", "Grafana", "Loki", "Docker", "Kubernetes", "AWS", "ArgoCD"],
    libraries: ["pandas", "NumPy", "Matplotlib", "PyTorch", "TensorFlow", "NLTK", "spaCy", "FastAPI", "Kafka"],
    databases: ["MySQL", "Oracle Database", "MongoDB", "Firebase", "PostgreSQL", "Neo4j"],
  },
  skillsCore: {
    languages: ["Python", "TypeScript", "Java", "C/C++"],
    infrastructure: ["Docker", "Kubernetes", "PostgreSQL", "Neo4j", "Kafka", "AWS"],
    ml: ["PyTorch", "LangGraph", "FastAPI", "PySpark"],
  },
  experience: [
    {
      title: "Full-stack AI Engineer",
      type: "Contract",
      company: "Monash University",
      period: "Nov 2025 – Feb 2026",
      tech: ["LangGraph", "Neo4j", "FastAPI"],
      bullets: [
        `${METRICS.monashRetrieval.impact} — self-correcting Text-to-Cypher over a Neo4j graph of ${METRICS.monashRetrieval.corpus}.`,
        "Hybrid retrieval: embeddings plus multi-hop graph walks for prerequisites and credit-transfer.",
        `A graph-logic SLM distilled from that reasoning: ${METRICS.slmLatency.display}, contradictions surfaced for administrators.`,
      ],
      impact: METRICS.monashRetrieval.impact,
    },
    {
      title: "Full-stack Engineer",
      type: "Contract Employee",
      company: "Western Digital",
      period: "Feb 2025 – Dec 2025",
      tech: ["Next.js", "ASP.NET", "PostgreSQL", "Docker"],
      bullets: [
        `${METRICS.wdOversight.display} — lab dashboard with role-based access for 50+ staff.`,
        "CRUD and analytics behind those roles.",
        "WebSocket to the lab's deep-learning model; shortest path between stations in under 100 ms on that dashboard path.",
      ],
      impact: "-40% manual oversight",
    },
    {
      title: "Software Engineer Intern",
      type: "Intern",
      company: "Setel",
      period: "Jul 2025 – Dec 2025",
      tech: ["Docker", "Kubernetes", "MERN Stack", "Swagger", "NestJS"],
      bullets: [
        "Authorization and capture of stored payment methods on the payment engine.",
        "Checkout and capture documented so a new developer could follow the path without a walkthrough.",
        `${METRICS.setelCoverage.display} on checkout and capture.`,
        `${METRICS.setelDefects.display} on that path (separate observation, not claimed as the coverage's effect).`,
      ],
      impact: METRICS.setelDefects.display,
    },
    {
      title: "Project Engineer Intern",
      type: "Intern",
      company: "Petronas",
      period: "Nov 2024 – Feb 2025",
      tech: ["MATLAB", "Python", "MathCAD"],
      bullets: [
        "Converted the department's MATLAB back-end to Python, replacing paid licences with free packages.",
        "Wrote user test cases for features after they reached production.",
        "Presented usability findings to department leadership.",
      ],
      impact: "Migrated MATLAB back-end to Python, replacing paid licences",
    },
  ],
  projects: [
    {
      name: "Veridian",
      slug: "veridian",
      subtitle: "MLOps Tradeoff Engine",
      purpose: "Intercepts Terraform and Kubernetes and names a lower-carbon box before the spike.",
      date: "Apr 2026",
      tech: ["Python", "Terraform", "BigQuery", "GCP Vertex AI", "GitLab Duo", "MCP"],
      bullets: [
        `${METRICS.veridianUptime.display} on Cloud Run, with ${METRICS.veridianEmissions.display} from scheduling that runs before the spike.`,
        "GitLab Duo + MCP intercept Terraform and Kubernetes as they change.",
        "Vertex AI names a quantized, lower-carbon box for the model on the desk.",
        "BigQuery holds the ESG ledger; it is not on the request.",
      ],
      impact: "Zero-touch ML remediation",
      why: "MCP here means the Terraform change is read as it is written, before the box is already running.",
      constraint: "The carbon ledger sits beside the request, not on it.",
      limitation: "No public repository. 99.9% uptime and −15% emissions are evaluations on Cloud Run, not a named production SLO.",
      evidenceNote: METRICS.veridianUptime.note,
      evidenceKind: METRICS.veridianUptime.kind,
      github: "",
      plate: "/plates/plate-veridian.jpg",
      plateCaption: "Veridian intercepts the change — file photo.",
      plateAlt: "Halftone photograph: an engineer at a drafting table, an infrastructure drawing unrolled before him.",
      description:
        "GitLab Duo intercepts the Terraform change; an MCP server on Cloud Run asks Vertex what the model needs; BigQuery keeps the carbon ledger off that request.",
      judgment: "The carbon ledger sits beside the request, not on it.",
      meta: "GitLab Duo intercepts Terraform; Vertex names a lower-carbon box; BigQuery keeps the carbon ledger off the request.",
      patent: VERIDIAN_PLANT satisfies ApparatusSpec,
      apparatus: {
        name: "Veridian",
        runtime: "Cloud Run",
        path: [
          { name: "GitLab Duo + MCP", role: "intercepts Terraform / K8s" },
          { name: "Vertex AI", role: "profile the model" },
        ],
        beside: [
          { name: "BigQuery", role: "ESG ledger — not this request" },
          { name: "Python", role: "glue, not a hop" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "CircuitMindAI",
      slug: "circuitmindai",
      subtitle: "PCB Inspection",
      purpose: "Inspects circuit boards: vision on the copper, voice for the operator.",
      date: "Mar 2026",
      tech: ["Next.js", "AWS Bedrock", "Express", "Amazon OSS", "GitHub Actions"],
      bullets: [
        "Nova Pro reads the copper; Nova Sonic talks the operator through the fault.",
        "Next.js and Express on ECS Fargate, with GitHub Actions stamping ECR.",
        "Edge cache holds the inspection when the network drops.",
        "A REST API for the line, not a slogan about performance.",
      ],
      impact: "PCB fault detection",
      inspectNote: "Express API (backend-js/) and Next.js UI (frontend/).",
      github: "https://github.com/Mizore66/CircuitMindAI",
      plate: "/plates/plate-circuitmind.jpg",
      plateCaption: "CircuitMindAI under the loupe — file photo.",
      plateAlt: "Halftone photograph: a printed circuit board under a loupe, traces filling the frame.",
      description:
        "CircuitMindAI inspects circuit boards: Nova Pro reads the copper, Nova Sonic talks the operator through the fault. Next.js and Express sit on ECS Fargate; GitHub Actions stamps the image.",
      judgment: "Edge cache holds the inspection when the network drops.",
      constraint: "The line has to keep the inspection when the network drops.",
      limitation: "No live host. The argument is this exhibit and the public repository.",
      meta: "Nova Pro reads the copper; Nova Sonic talks the operator through the fault. Next.js and Express on ECS Fargate.",
      patent: CIRCUITMIND_LINE satisfies ApparatusSpec,
      apparatus: {
        name: "CircuitMindAI",
        runtime: "ECS Fargate",
        path: [
          { name: "Next.js", role: "UI" },
          { name: "Express", role: "API" },
        ],
        forks: [
          { name: "Bedrock Nova", role: "vision + voice" },
          { name: "OpenSearch", role: "index" },
        ],
        beside: [{ name: "GitHub Actions", role: "CI/CD to ECR" }],
      } satisfies Apparatus,
    },
    {
      name: "MirrorFi",
      slug: "mirrorfi",
      subtitle: "Solana Vault Strategy Platform",
      purpose: "A desk for drawing, sharing, and firing Solana vault lines.",
      date: "May 2025",
      tech: ["Next.js", "Node.js", "MongoDB", "Solana", "ShadCN"],
      bullets: [
        "Grand Prize, Solana Megahack 2025 — a desk for drawing, sharing, and firing vault lines.",
        "Drift, Jupiter, and Meteora in one schematic.",
        "MongoDB stores the copy so another desk can run it.",
        "A governor rebalances the pool when APY moves.",
      ],
      impact: "Grand Prize Winner",
      contextLabel: "Grand Prize, Solana Megahack 2025",
      inspectNote: "Source is the public Megahack repository.",
      github: "https://github.com/Mizore66/MirrorFi",
      plate: "/plates/plate-mirrorfi.jpg",
      plateCaption: "MirrorFi at the vault wall — file photo.",
      plateAlt: "Halftone photograph: a vault door and lock-work, lit like a bank interior.",
      description:
        "A Next.js desk draws the vault line; Node.js talks to Drift, Jupiter, and Meteora; MongoDB stores the copy so another desk can run it.",
      constraint: "A hackathon desk: drawing, sharing, and firing vault lines in one schematic.",
      limitation: "No live host. Source is the public Megahack repository.",
      meta: "A desk for drawing, sharing, and firing Solana vault lines. Drift, Jupiter and Meteora in one schematic. Grand Prize, Megahack 2025.",
      patent: MIRRORFI_VAULT satisfies ApparatusSpec,
      apparatus: {
        name: "MirrorFi",
        path: [
          { name: "Next.js", role: "no-code UI" },
          { name: "Node.js", role: "API" },
        ],
        forks: [
          { name: "MongoDB", role: "shareable strategies" },
          { name: "Solana", role: "Drift · Jupiter · Meteora" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "Multi-Agent GraphRAG",
      slug: "multi-agent-graphrag",
      subtitle: "Policy-corpus retrieval",
      purpose: "LangGraph over the university's policy corpus, with a vector fallback.",
      date: "Oct 2025",
      tech: ["LangGraph", "Neo4j", "Vector DB", "Knowledge Graphs", "RAG"],
      bullets: [
        `${METRICS.graphragRetrieval.impact} — ${METRICS.graphragRetrieval.method}.`,
        "Cypher written by the agent, then checked, on the university's policy corpus.",
        "Global-to-local retrieval when the question spans the handbook.",
        "Ambiguous questions fall back to a broader semantic search.",
      ],
      impact: METRICS.graphragRetrieval.impact,
      evidenceNote: METRICS.graphragRetrieval.note,
      evidenceKind: METRICS.graphragRetrieval.kind,
      github: "",
      plate: "/plates/plate-graphrag.jpg",
      plateCaption: "GraphRAG at the card catalog — file photo.",
      plateAlt: "Halftone photograph: wooden card-catalog drawers, one drawer open on a labelled card.",
      description:
        "LangGraph asks Neo4j for the university's policy corpus, then a vector store when the graph is silent. Agents write Cypher, check it, and try again.",
      judgment:
        "The graph is the structured path for prerequisites and policy; the vector store is the fallback when the graph is silent.",
      why: "A question about prerequisites has to walk the graph, not only the nearest paragraph.",
      constraint: "Prerequisites and credit-transfer are edges, not another embedding dump.",
      limitation: "Ambiguous questions fall back to a broader semantic search. Sample size and Recall@k were not filed.",
      split: RETRIEVAL_SPLIT,
      meta: `LangGraph over the university's policy corpus: agents write Cypher, check it, and fall back to a vector store. ${METRICS.graphragRetrieval.strip}.`,
      patent: VERIDIAN_EXCHANGE satisfies ApparatusSpec,
      apparatus: {
        name: "Multi-Agent GraphRAG",
        path: [{ name: "LangGraph", role: "orchestrator" }],
        forks: [
          { name: "Neo4j", role: "structured" },
          { name: "Vector DB", role: "unstructured" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "Financial Risk Predictor",
      slug: "financial-risk-predictor",
      subtitle: "ML Risk Assessment",
      purpose: "Daily credit-risk scores that have to be interpreted, served, and retrained.",
      date: "Jul 2025",
      tech: ["TensorFlow", "XGBoost", "LightGBM", "BentoML", "SHAP"],
      bullets: [
        `${METRICS.riskAuc.display} — ${METRICS.riskAuc.vs}, LightGBM and XGBoost.`,
        "SHAP names the drivers on the score.",
        "−30% inference latency on the BentoML hatch.",
        "Daily retrain from Kafka so the score is this morning's tape.",
      ],
      impact: "0.87 AUC-ROC score",
      evidenceNote: METRICS.riskAuc.note,
      evidenceKind: METRICS.riskAuc.kind,
      limitation: "15% over the baseline as filed; the baseline model was not named beyond that comparison.",
      github: "",
      plate: "/plates/plate-risk.jpg",
      plateCaption: "Financial Risk Predictor — the ledger, file photo.",
      plateAlt: "Halftone photograph: an open ledger with ruled columns, a pen resting on the page.",
      description:
        "Kafka feeds the daily tape; LightGBM and XGBoost score it; SHAP writes why; BentoML serves the number.",
      meta: "Kafka feeds the daily tape. LightGBM and XGBoost score it at 0.87 AUC. SHAP writes why. BentoML serves the number.",
      patent: RISK_ENGINE satisfies ApparatusSpec,
      apparatus: {
        name: "Financial Risk Predictor",
        path: [
          { name: "Kafka", role: "daily retrain" },
          { name: "LightGBM / XGBoost", role: "0.87 AUC" },
          { name: "BentoML", role: "serving API" },
        ],
        beside: [{ name: "SHAP", role: "why the score" }],
      } satisfies Apparatus,
    },
    {
      name: "Distributed Lead Scorer",
      slug: "distributed-lead-scorer",
      subtitle: "Large-Scale Data Mining Pipeline",
      purpose: "Scores conversion on a hundred million events a day without losing the tape.",
      date: "May 2025",
      tech: ["PyTorch DDP", "PySpark", "Deep Interest Network", "Distributed Computing"],
      bullets: [
        `${METRICS.leadThroughput.display} on PySpark — hours of latency cut to minutes.`,
        "Deep Interest Network on PyTorch DDP across the GPU cluster.",
        "Automated evaluation so a bad net does not ship.",
        "Checkpoints: zero tape lost on a multi-hour run.",
      ],
      impact: "100M events/day processed",
      evidenceNote: METRICS.leadThroughput.note,
      evidenceKind: METRICS.leadThroughput.kind,
      constraint: "Checkpoints so a dead job does not lose the tape.",
      limitation: "Pipeline / capacity. Not claimed as sustained production volume.",
      github: "",
      plate: "/plates/plate-leads.jpg",
      plateCaption: "Distributed Lead Scorer — the sorting hall, file photo.",
      plateAlt: "Halftone photograph: a mail-sorting hall, pigeonholes stretching into the distance.",
      description:
        "PySpark sorts 100M events/day into features; a Deep Interest Network on PyTorch DDP scores conversion; checkpoints so a dead job does not lose the tape.",
      meta: "PySpark sorts 100M events a day. A Deep Interest Network on PyTorch DDP scores conversion. Checkpoints so a dead job keeps the tape.",
      patent: LEADS_HALL satisfies ApparatusSpec,
      apparatus: {
        name: "Distributed Lead Scorer",
        path: [
          { name: "PySpark", role: "100M+ events / day" },
          { name: "PyTorch DDP", role: "Deep Interest Network" },
        ],
      } satisfies Apparatus,
    },
    {
      name: "SLM Distillation Engine",
      slug: "slm-distillation-engine",
      subtitle: "Knowledge Distillation & Fine-Tuning",
      purpose: "A 70B teacher compressed into a 3B student that keeps the same job.",
      date: "Jul 2025",
      tech: ["PyTorch", "QLoRA", "DeepSpeed", "FlashAttention"],
      bullets: [
        `${METRICS.slmInference.display} — 70B teacher into a 3B student.`,
        "QLoRA on the domain set.",
        "−40% memory with DeepSpeed and FlashAttention.",
        "98% pass on the edge-case reward metric.",
      ],
      impact: METRICS.slmInference.impact,
      why: "I used QLoRA to distil traces from a 70B teacher into a deployable 3B student.",
      constraint: "The student had to keep the same job on a smaller piece.",
      limitation: "12x inference is an evaluation on the 70B to 3B path, not a production serving number.",
      evidenceNote: METRICS.slmInference.note,
      evidenceKind: METRICS.slmInference.kind,
      github: "",
      plate: "/plates/plate-slm.jpg",
      plateCaption: "SLM Distillation — teacher and student machines, file photo.",
      plateAlt: "Halftone photograph: two machines side by side, the smaller one cabled to the larger.",
      description:
        "A 70B teacher writes the traces; QLoRA, DeepSpeed and FlashAttention compress them into a 3B student that keeps the same job.",
      meta: "A 70B teacher writes the traces; QLoRA, DeepSpeed and FlashAttention compress them into a 3B student. 12× inference.",
      patent: VERIDIAN_STILL satisfies ApparatusSpec,
      apparatus: {
        name: "SLM Distillation Engine",
        runtime: "DeepSpeed",
        path: [
          { name: "70B teacher", role: "source" },
          { name: "QLoRA", role: "distill" },
          { name: "3B SLM", role: "12× inference" },
        ],
        beside: [{ name: "FlashAttention", role: "memory" }],
      } satisfies Apparatus,
    },
  ],
};
