import type { ApparatusSpec } from "@/lib/opening/types";

/** Overlay percents are of the engraving box. Furniture is HTML/SVG around it. */
const SHEET = { w: 720, h: 540 };
const ENGRAVING = { width: 1400, height: 1050 };

export const FIGURES = {
  e4: {
    fig: 1,
    move: "1. e4",
    function: "AN ENGINEERING EDUCATION",
    filed: "May 2026",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6],
    engraving: { src: "/figures/fig-e4.webp", ...ENGRAVING },
    review: {
      status: "validated",
      notes:
        "Metaphor-only, as approved. Crucible/molds/cases are not a campus architecture. Degree metrics are résumé-public; the foundry mapping is presumed.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "the curriculum", confidence: "presumed" },
      { n: 2, glyph: "crucible", label: "CRUCIBLE", mapsTo: "data structures", confidence: "presumed" },
      { n: 3, glyph: "funnel", label: "FUNNEL", mapsTo: "lectures into practice", confidence: "presumed" },
      { n: 4, glyph: "mold", label: "MOLD", mapsTo: "systems", confidence: "presumed" },
      { n: 5, glyph: "roller", label: "ROLLER", mapsTo: "the press of coursework", confidence: "presumed" },
      { n: 6, glyph: "typecase", label: "TYPE CASE", mapsTo: "theory", confidence: "presumed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "WAM 82.1 · CGPA 3.82", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "the degree, May 2026", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 16, y: 6, fromX: 22, fromY: 16, glyph: "hopper" },
      { mark: "2", x: 6, y: 28, fromX: 16, fromY: 34, glyph: "crucible" },
      { mark: "3", x: 30, y: 18, fromX: 34, fromY: 32, glyph: "funnel" },
      { mark: "4", x: 52, y: 16, fromX: 54, fromY: 32, glyph: "mold" },
      { mark: "4a", x: 14, y: 72, fromX: 22, fromY: 82, glyph: "mold" },
      { mark: "5", x: 82, y: 22, fromX: 78, fromY: 36, glyph: "roller" },
      { mark: "6", x: 92, y: 68, fromX: 82, fromY: 80, glyph: "typecase" },
      { mark: "6a", x: 90, y: 84, fromX: 80, fromY: 86, glyph: "typecase" },
      { mark: "7", x: 92, y: 8, fromX: 84, fromY: 16, glyph: "gauge" },
      { mark: "8", x: 50, y: 68, fromX: 50, fromY: 80, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 62 },
      { n: 2, x: 3, y: 96, caption: "vertical section of the mold" },
    ],
    detail: { title: "vertical section of the mold" },
  },
  nf3: {
    fig: 2,
    move: "2. Nf3",
    function: "RE-POWERING A MILL",
    filed: "Nov. 2024",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 5, 3, 4, 7],
    engraving: { src: "/figures/fig-nf3.webp", ...ENGRAVING },
    review: {
      status: "validated",
      notes:
        "Petronas, generic names only. Licensed mill → open-source mill is the public MATLAB→Python overhaul. Belts are the test cases. Ledger is −20% cost. No internal plant names.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "source models", confidence: "presumed" },
      { n: 2, glyph: "millwheel", label: "MILLWHEEL", mapsTo: "licensed mill, idle", confidence: "confirmed" },
      { n: 3, glyph: "belt", label: "BELT", mapsTo: "test suite proving identical output", confidence: "confirmed" },
      { n: 4, glyph: "boiler", label: "BOILER", mapsTo: "open-source mill", confidence: "confirmed" },
      { n: 5, glyph: "valve", label: "VALVE", mapsTo: "cutover", confidence: "presumed" },
      { n: 6, glyph: "funnel", label: "FUNNEL", mapsTo: "desk mill, not this path", confidence: "confirmed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "+30% efficiency", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "−20% department cost", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 20, y: 4, fromX: 26, fromY: 14, glyph: "hopper" },
      { mark: "2", x: 4, y: 20, fromX: 14, fromY: 34, glyph: "millwheel" },
      { mark: "2a", x: 6, y: 66, fromX: 16, fromY: 62, glyph: "millwheel" },
      { mark: "3", x: 46, y: 32, fromX: 50, fromY: 44, glyph: "belt" },
      { mark: "3a", x: 62, y: 76, fromX: 62, fromY: 88, glyph: "belt" },
      { mark: "4", x: 78, y: 36, fromX: 82, fromY: 50, glyph: "boiler" },
      { mark: "4a", x: 86, y: 4, fromX: 80, fromY: 16, glyph: "boiler" },
      { mark: "5", x: 58, y: 6, fromX: 66, fromY: 18, glyph: "valve" },
      { mark: "6", x: 96, y: 38, fromX: 92, fromY: 50, glyph: "funnel" },
      { mark: "7", x: 48, y: 50, fromX: 50, fromY: 60, glyph: "gauge" },
      { mark: "8", x: 8, y: 76, fromX: 16, fromY: 86, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 64 },
      { n: 2, x: 48, y: 96, caption: "section of the driving pulley" },
    ],
    detail: { title: "section of the driving pulley" },
  },
  nc6: {
    fig: 3,
    move: "2…Nc6",
    function: "A PNEUMATIC-TUBE EXCHANGE",
    filed: "Jul. 2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6, 7],
    engraving: { src: "/figures/fig-nc6.webp", ...ENGRAVING },
    review: {
      status: "validated",
      notes:
        "Setel payments, generic names only. Authorization and capture are résumé-public. Capsules are transactions. One-capsule-per-tube is presumed idempotency. Seal is 92.5% coverage.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "INTAKE", mapsTo: "checkout", confidence: "presumed" },
      { n: 2, glyph: "valve", label: "VALVE", mapsTo: "authorization", confidence: "confirmed" },
      { n: 3, glyph: "tube", label: "TUBE", mapsTo: "the conduit", confidence: "presumed" },
      { n: 4, glyph: "capsule", label: "CAPSULE", mapsTo: "a payment", confidence: "confirmed" },
      { n: 5, glyph: "governor", label: "GOVERNOR", mapsTo: "one capsule per tube", confidence: "presumed" },
      { n: 6, glyph: "vault", label: "VAULT", mapsTo: "capture", confidence: "confirmed" },
      { n: 7, glyph: "seal", label: "SEAL PRESS", mapsTo: "92.5% coverage", confidence: "confirmed" },
      { n: 8, glyph: "gauge", label: "GAUGE", mapsTo: "−40% production defects", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 6, y: 14, fromX: 14, fromY: 24, glyph: "hopper" },
      { mark: "2", x: 22, y: 6, fromX: 28, fromY: 16, glyph: "valve" },
      { mark: "3", x: 6, y: 48, fromX: 16, fromY: 40, glyph: "tube" },
      { mark: "3a", x: 28, y: 74, fromX: 32, fromY: 86, glyph: "tube" },
      { mark: "4", x: 40, y: 26, fromX: 46, fromY: 38, glyph: "capsule" },
      { mark: "5", x: 50, y: 4, fromX: 50, fromY: 16, glyph: "governor" },
      { mark: "6", x: 66, y: 16, fromX: 70, fromY: 32, glyph: "vault" },
      { mark: "6a", x: 82, y: 52, fromX: 76, fromY: 46, glyph: "vault" },
      { mark: "7", x: 94, y: 16, fromX: 90, fromY: 28, glyph: "seal" },
      { mark: "8", x: 80, y: 6, fromX: 74, fromY: 18, glyph: "gauge" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 62 },
      { n: 2, x: 18, y: 96, caption: "station cut open, capsule in transit" },
    ],
    detail: { title: "station cut open, capsule in transit" },
  },
  bc4: {
    fig: 4,
    move: "3. Bc4",
    function: "A LABORATORY CONTROL CONSOLE",
    filed: "Feb. 2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6, 7, 8],
    engraving: { src: "/figures/fig-bc4.webp", ...ENGRAVING },
    review: {
      status: "validated",
      notes:
        "Western Digital, generic names only. Gauge panel is lab systems. Three keys are the public RBAC roles. Telegraph is the live line to the model. Relay is <100 ms.",
    },
    parts: [
      { n: 1, glyph: "gaugepanel", label: "GAUGE PANEL", mapsTo: "lab systems", confidence: "confirmed" },
      { n: 2, glyph: "key", label: "KEY", mapsTo: "administrator", confidence: "confirmed" },
      { n: 3, glyph: "key", label: "KEY", mapsTo: "operator", confidence: "confirmed" },
      { n: 4, glyph: "key", label: "KEY", mapsTo: "superuser", confidence: "confirmed" },
      { n: 5, glyph: "telegraph", label: "TELEGRAPH", mapsTo: "live line to the model", confidence: "confirmed" },
      { n: 6, glyph: "tube", label: "LINE", mapsTo: "the wire", confidence: "presumed" },
      { n: 7, glyph: "relay", label: "RELAY", mapsTo: "<100 ms", confidence: "confirmed" },
      { n: 8, glyph: "boiler", label: "DISTANT MILL", mapsTo: "the model", confidence: "presumed" },
    ],
    numerals: [
      { mark: "1", x: 8, y: 8, fromX: 16, fromY: 22, glyph: "gaugepanel" },
      { mark: "1a", x: 28, y: 8, fromX: 36, fromY: 22, glyph: "gaugepanel" },
      { mark: "2", x: 10, y: 46, fromX: 18, fromY: 40, glyph: "key" },
      { mark: "3", x: 28, y: 46, fromX: 34, fromY: 40, glyph: "key" },
      { mark: "4", x: 44, y: 46, fromX: 48, fromY: 40, glyph: "key" },
      { mark: "5", x: 66, y: 52, fromX: 62, fromY: 44, glyph: "telegraph" },
      { mark: "6", x: 78, y: 26, fromX: 80, fromY: 36, glyph: "tube" },
      { mark: "7", x: 62, y: 12, fromX: 64, fromY: 22, glyph: "relay" },
      { mark: "7a", x: 48, y: 70, fromX: 50, fromY: 84, glyph: "relay" },
      { mark: "8", x: 92, y: 32, fromX: 88, fromY: 40, glyph: "boiler" },
      { mark: "8a", x: 94, y: 6, fromX: 90, fromY: 16, glyph: "boiler" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 64 },
      { n: 2, x: 18, y: 96, caption: "the relay, enlarged" },
    ],
    detail: { title: "the relay, enlarged" },
  },
  oo: {
    fig: 5,
    move: "4. O-O",
    function: "CASTLING",
    filed: "2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [2, 3, 1, 4, 5, 6, 7],
    engraving: { src: "/figures/fig-oo.webp", ...ENGRAVING },
    review: {
      status: "validated",
      notes:
        "Reliability chapter mapped onto a Watt governor. The three proofs are résumé-public: 92.5% coverage, role-based access, 99.9% uptime.",
    },
    parts: [
      { n: 1, glyph: "governor", label: "GOVERNOR", mapsTo: "king safety", confidence: "presumed" },
      { n: 2, glyph: "boiler", label: "BOILER", mapsTo: "the plant still running", confidence: "presumed" },
      { n: 3, glyph: "belt", label: "BELT", mapsTo: "proofs coupled to the shaft", confidence: "presumed" },
      { n: 4, glyph: "valve", label: "VALVE", mapsTo: "throttle before the break", confidence: "presumed" },
      { n: 5, glyph: "gauge", label: "GAUGE", mapsTo: "92.5% coverage", confidence: "confirmed" },
      { n: 6, glyph: "key", label: "KEY", mapsTo: "role-based access", confidence: "confirmed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "99.9% uptime", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "the reliability proofs", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 50, y: 4, fromX: 50, fromY: 16, glyph: "governor" },
      { mark: "1a", x: 32, y: 22, fromX: 38, fromY: 34, glyph: "governor" },
      { mark: "1b", x: 64, y: 22, fromX: 58, fromY: 34, glyph: "governor" },
      { mark: "1c", x: 90, y: 4, fromX: 84, fromY: 16, glyph: "governor" },
      { mark: "2", x: 6, y: 42, fromX: 16, fromY: 52, glyph: "boiler" },
      { mark: "2a", x: 6, y: 6, fromX: 12, fromY: 16, glyph: "boiler" },
      { mark: "3", x: 26, y: 56, fromX: 34, fromY: 62, glyph: "belt" },
      { mark: "4", x: 72, y: 62, fromX: 66, fromY: 70, glyph: "valve" },
      { mark: "5", x: 94, y: 36, fromX: 84, fromY: 42, glyph: "gauge" },
      { mark: "6", x: 94, y: 64, fromX: 86, fromY: 70, glyph: "key" },
      { mark: "7", x: 94, y: 50, fromX: 84, fromY: 56, glyph: "gauge" },
      { mark: "8", x: 90, y: 80, fromX: 84, fromY: 86, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 64 },
      { n: 2, x: 72, y: 4, caption: "vertical section of the flyball head" },
    ],
    detail: { title: "vertical section of the flyball head" },
  },
} as const satisfies Record<string, ApparatusSpec>;

export const VERIDIAN_PRESS: ApparatusSpec = {
  fig: 6,
  move: "5. d4",
  function: "PRINTING THE MORNING EDITION",
  filed: "Apr. 2026",
  viewBox: SHEET,
  layout: "elevation",
  flow: [1, 2, 3, 4, 5, 6, 7],
  engraving: { src: "/figures/fig-d4.webp", ...ENGRAVING },
  review: {
    status: "validated",
    notes:
      "Veridian exhibit. Paper stock = infrastructure plans; composing room = graph retrieval; stereotype = distilled model; edition = recommendations. 99.9% uptime is résumé-public.",
  },
  parts: [
    { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "paper stock — infrastructure plans", confidence: "confirmed" },
    { n: 2, glyph: "funnel", label: "FUNNEL", mapsTo: "the intercept", confidence: "presumed" },
    { n: 3, glyph: "typecase", label: "COMPOSING ROOM", mapsTo: "graph retrieval", confidence: "confirmed" },
    { n: 4, glyph: "mold", label: "STEREOTYPE", mapsTo: "distilled model", confidence: "confirmed" },
    { n: 5, glyph: "roller", label: "ROLLER", mapsTo: "the press", confidence: "presumed" },
    { n: 6, glyph: "belt", label: "BELT", mapsTo: "the run", confidence: "presumed" },
    { n: 7, glyph: "ledger", label: "EDITION", mapsTo: "the morning recommendations", confidence: "confirmed" },
    { n: 8, glyph: "gauge", label: "GAUGE", mapsTo: "99.9% uptime", confidence: "confirmed" },
  ],
  numerals: [
    { mark: "1", x: 10, y: 6, fromX: 18, fromY: 16, glyph: "hopper" },
    { mark: "2", x: 30, y: 24, fromX: 34, fromY: 34, glyph: "funnel" },
    { mark: "3", x: 8, y: 38, fromX: 18, fromY: 46, glyph: "typecase" },
    { mark: "4", x: 50, y: 78, fromX: 50, fromY: 92, glyph: "mold" },
    { mark: "5", x: 46, y: 24, fromX: 52, fromY: 38, glyph: "roller" },
    { mark: "5a", x: 62, y: 42, fromX: 56, fromY: 48, glyph: "roller" },
    { mark: "6", x: 82, y: 22, fromX: 78, fromY: 36, glyph: "belt" },
    { mark: "7", x: 96, y: 36, fromX: 90, fromY: 44, glyph: "ledger" },
    { mark: "7a", x: 96, y: 50, fromX: 90, fromY: 46, glyph: "ledger" },
    { mark: "8", x: 78, y: 8, fromX: 72, fromY: 20, glyph: "gauge" },
  ],
  figLabels: [
    { n: 1, x: 3, y: 64 },
    { n: 2, x: 18, y: 96, caption: "the stereotype plate" },
  ],
  detail: { title: "the stereotype plate" },
};
