import type { ApparatusSpec } from "@/lib/opening/types";

/** Overlay percents are of the engraving box. Furniture is HTML/SVG around it. */
const SHEET = { w: 720, h: 540 };
const ENGRAVING = { width: 1400, height: 1050 };

export const FIGURES = {
  e4: {
    fig: 1,
    move: "1. e4",
    function: "AN ENGINEERING EDUCATION",
    filed: "May 2026",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6],
    engraving: {
      src: "/figures/fig-e4.webp",
      ...ENGRAVING,
      alt: "Patent-style engraving: a foundry in numbered parts — hopper, crucible, funnel, molds, roller, type case, and gauges.",
    },
    review: {
      status: "validated",
      notes:
        "Metaphor-only, as approved. Crucible/molds/cases are not a campus architecture. Degree metrics are résumé-public; the foundry mapping is presumed.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "the curriculum", confidence: "presumed" },
      { n: 2, glyph: "crucible", label: "CRUCIBLE", mapsTo: "data structures", confidence: "presumed" },
      { n: 3, glyph: "funnel", label: "FUNNEL", mapsTo: "lectures into practice", confidence: "presumed" },
      { n: 4, glyph: "mold", label: "MOLD", mapsTo: "systems", confidence: "presumed" },
      { n: 5, glyph: "roller", label: "ROLLER", mapsTo: "the press of coursework", confidence: "presumed" },
      { n: 6, glyph: "typecase", label: "TYPE CASE", mapsTo: "theory", confidence: "presumed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "WAM 82.1 · CGPA 3.82", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "the degree, May 2026", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 31.0, y: 8.0, fromX: 26.1, fromY: 12.4, glyph: "hopper" },
      { mark: "2", x: 3.0, y: 34.0, fromX: 15.6, fromY: 34.0, glyph: "crucible" },
      { mark: "3", x: 39.0, y: 8.0, fromX: 34.2, fromY: 31.2, glyph: "funnel" },
      { mark: "4", x: 53.0, y: 8.0, fromX: 54.0, fromY: 31.2, glyph: "mold" },
      { mark: "4a", x: 23.0, y: 94.0, fromX: 22.0, fromY: 82.4, glyph: "mold" },
      { mark: "5", x: 93.0, y: 36.0, fromX: 82.3, fromY: 36.0, glyph: "roller" },
      { mark: "6", x: 81.0, y: 92.0, fromX: 82.0, fromY: 80.4, glyph: "typecase" },
      { mark: "6a", x: 75.0, y: 94.0, fromX: 79.8, fromY: 86.3, glyph: "typecase" },
      { mark: "7", x: 93.0, y: 16.0, fromX: 84.9, fromY: 16.0, glyph: "gauge" },
      { mark: "8", x: 57.0, y: 92.0, fromX: 50.2, fromY: 80.4, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 62 },
      { n: 2, x: 3, y: 96, caption: "vertical section of the mold" },
    ],
    detail: { title: "vertical section of the mold" },
  },
  nf3: {
    fig: 2,
    move: "2. Nf3",
    function: "RE-POWERING A MILL",
    filed: "Nov. 2024",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 5, 3, 4, 7],
    engraving: {
      src: "/figures/fig-nf3.webp",
      ...ENGRAVING,
      alt: "Patent-style engraving: a mill in numbered parts — hopper, millwheel, belts, boiler, valve, and gauges.",
    },
    review: {
      status: "validated",
      notes:
        "Petronas, generic names only. Licensed mill → open-source mill is the public MATLAB→Python overhaul. Belts are the test cases. Ledger is −20% cost. No internal plant names.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "source models", confidence: "presumed" },
      { n: 2, glyph: "millwheel", label: "MILLWHEEL", mapsTo: "licensed mill, idle", confidence: "confirmed" },
      { n: 3, glyph: "belt", label: "BELT", mapsTo: "test suite proving identical output", confidence: "confirmed" },
      { n: 4, glyph: "boiler", label: "BOILER", mapsTo: "open-source mill", confidence: "confirmed" },
      { n: 5, glyph: "valve", label: "VALVE", mapsTo: "cutover", confidence: "presumed" },
      { n: 6, glyph: "funnel", label: "FUNNEL", mapsTo: "desk mill, not this path", confidence: "confirmed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "+30% efficiency", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "−20% department cost", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 25.0, y: 6.0, fromX: 25.8, fromY: 12.2, glyph: "hopper" },
      { mark: "2", x: 7.0, y: 34.0, fromX: 13.6, fromY: 34.0, glyph: "millwheel" },
      { mark: "2a", x: 5.0, y: 54.0, fromX: 11.1, fromY: 58.4, glyph: "millwheel" },
      { mark: "3", x: 51.0, y: 22.0, fromX: 50.0, fromY: 43.3, glyph: "belt" },
      { mark: "3a", x: 71.0, y: 92.0, fromX: 62.3, fromY: 88.1, glyph: "belt" },
      { mark: "4", x: 93.0, y: 50.0, fromX: 87.0, fromY: 50.0, glyph: "boiler" },
      { mark: "4a", x: 85.0, y: 8.0, fromX: 81.3, fromY: 13.9, glyph: "boiler" },
      { mark: "5", x: 65.0, y: 8.0, fromX: 66.0, fromY: 17.7, glyph: "valve" },
      { mark: "6", x: 97.0, y: 44.0, fromX: 92.2, fromY: 49.8, glyph: "funnel" },
      { mark: "7", x: 35.0, y: 88.0, fromX: 49.5, fromY: 60.9, glyph: "gauge" },
      { mark: "8", x: 7.0, y: 86.0, fromX: 15.7, fromY: 86.0, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 74 },
      { n: 2, x: 48, y: 96, caption: "section of the driving pulley" },
    ],
    detail: { title: "section of the driving pulley" },
  },
  nc6: {
    fig: 3,
    move: "2…Nc6",
    function: "A PNEUMATIC-TUBE EXCHANGE",
    filed: "Jul. 2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6, 7],
    engraving: {
      src: "/figures/fig-nc6.webp",
      ...ENGRAVING,
      alt: "Patent-style engraving: a pneumatic-tube exchange in numbered parts — intake, valve, tube, capsule, governor, vault, and seal press.",
    },
    review: {
      status: "validated",
      notes:
        "Setel payments, generic names only. Authorization and capture are résumé-public. Capsules are transactions. One-capsule-per-tube is presumed idempotency. Seal is 92.5% coverage.",
    },
    parts: [
      { n: 1, glyph: "hopper", label: "INTAKE", mapsTo: "checkout", confidence: "presumed" },
      { n: 2, glyph: "valve", label: "VALVE", mapsTo: "authorization", confidence: "confirmed" },
      { n: 3, glyph: "tube", label: "TUBE", mapsTo: "the conduit", confidence: "presumed" },
      { n: 4, glyph: "capsule", label: "CAPSULE", mapsTo: "a payment", confidence: "confirmed" },
      { n: 5, glyph: "governor", label: "GOVERNOR", mapsTo: "one capsule per tube", confidence: "presumed" },
      { n: 6, glyph: "vault", label: "VAULT", mapsTo: "capture", confidence: "confirmed" },
      { n: 7, glyph: "seal", label: "SEAL PRESS", mapsTo: "92.5% coverage", confidence: "confirmed" },
      { n: 8, glyph: "gauge", label: "GAUGE", mapsTo: "−40% production defects", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 5.0, y: 30.0, fromX: 13.7, fromY: 24.2, glyph: "hopper" },
      { mark: "2", x: 27.0, y: 8.0, fromX: 28.0, fromY: 15.7, glyph: "valve" },
      { mark: "3", x: 3.0, y: 36.0, fromX: 14.3, fromY: 39.5, glyph: "tube" },
      { mark: "3a", x: 35.0, y: 94.0, fromX: 32.9, fromY: 88.3, glyph: "tube" },
      { mark: "4", x: 45.0, y: 8.0, fromX: 46.0, fromY: 37.0, glyph: "capsule" },
      { mark: "5", x: 61.0, y: 8.0, fromX: 51.4, fromY: 15.0, glyph: "governor" },
      { mark: "6", x: 93.0, y: 32.0, fromX: 70.7, fromY: 32.0, glyph: "vault" },
      { mark: "6a", x: 97.0, y: 60.0, fromX: 76.7, fromY: 46.5, glyph: "vault" },
      { mark: "7", x: 93.0, y: 20.0, fromX: 90.1, fromY: 27.7, glyph: "seal" },
      { mark: "8", x: 73.0, y: 8.0, fromX: 74.0, fromY: 17.7, glyph: "gauge" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 62 },
      { n: 2, x: 18, y: 96, caption: "station cut open, capsule in transit" },
    ],
    detail: { title: "station cut open, capsule in transit" },
  },
  bc4: {
    fig: 4,
    move: "3. Bc4",
    function: "A LABORATORY CONTROL CONSOLE",
    filed: "Feb. 2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [1, 2, 3, 4, 5, 6, 7, 8],
    engraving: {
      src: "/figures/fig-bc4.webp",
      ...ENGRAVING,
      alt: "Patent-style engraving: a laboratory control console in numbered parts — gauge panel, three keys, telegraph, relay, and a distant mill.",
    },
    review: {
      status: "validated",
      notes:
        "Western Digital, generic names only. Gauge panel is lab systems. Three keys are the public RBAC roles. Telegraph is the live line to the model. Relay is <100 ms.",
    },
    parts: [
      { n: 1, glyph: "gaugepanel", label: "GAUGE PANEL", mapsTo: "lab systems", confidence: "confirmed" },
      { n: 2, glyph: "key", label: "KEY", mapsTo: "administrator", confidence: "confirmed" },
      { n: 3, glyph: "key", label: "KEY", mapsTo: "operator", confidence: "confirmed" },
      { n: 4, glyph: "key", label: "KEY", mapsTo: "superuser", confidence: "confirmed" },
      { n: 5, glyph: "telegraph", label: "TELEGRAPH", mapsTo: "live line to the model", confidence: "confirmed" },
      { n: 6, glyph: "tube", label: "LINE", mapsTo: "the wire", confidence: "presumed" },
      { n: 7, glyph: "relay", label: "RELAY", mapsTo: "<100 ms", confidence: "confirmed" },
      { n: 8, glyph: "boiler", label: "DISTANT MILL", mapsTo: "the model", confidence: "presumed" },
    ],
    numerals: [
      { mark: "1", x: 3.0, y: 20.0, fromX: 15.6, fromY: 21.9, glyph: "gaugepanel" },
      { mark: "1a", x: 35.0, y: 4.0, fromX: 36.0, fromY: 21.4, glyph: "gaugepanel" },
      { mark: "2", x: 3.0, y: 40.0, fromX: 17.5, fromY: 40.0, glyph: "key" },
      { mark: "3", x: 11.0, y: 32.0, fromX: 33.3, fromY: 39.7, glyph: "key" },
      { mark: "4", x: 55.0, y: 12.0, fromX: 48.2, fromY: 39.1, glyph: "key" },
      { mark: "5", x: 93.0, y: 40.0, fromX: 66.0, fromY: 43.5, glyph: "telegraph" },
      { mark: "6", x: 97.0, y: 24.0, fromX: 80.5, fromY: 35.6, glyph: "tube" },
      { mark: "7", x: 71.0, y: 8.0, fromX: 64.2, fromY: 21.6, glyph: "relay" },
      { mark: "7a", x: 59.0, y: 92.0, fromX: 51.7, fromY: 85.5, glyph: "relay" },
      { mark: "8", x: 93.0, y: 60.0, fromX: 89.0, fromY: 43.9, glyph: "boiler" },
      { mark: "8a", x: 97.0, y: 16.0, fromX: 90.2, fromY: 16.0, glyph: "boiler" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 64 },
      { n: 2, x: 18, y: 96, caption: "the relay, enlarged" },
    ],
    detail: { title: "the relay, enlarged" },
  },
  oo: {
    fig: 5,
    move: "4. O-O",
    function: "CASTLING",
    filed: "2025",
    viewBox: SHEET,
    layout: "elevation",
    flow: [2, 3, 1, 4, 5, 6, 7],
    engraving: {
      src: "/figures/fig-oo.webp",
      ...ENGRAVING,
      alt: "Patent-style engraving: a Watt governor in numbered parts — flyball head, boiler, belt, valve, keys, and gauges.",
    },
    review: {
      status: "validated",
      notes:
        "Reliability chapter mapped onto a Watt governor. The three proofs are résumé-public: 92.5% coverage, role-based access, 99.9% uptime.",
    },
    parts: [
      { n: 1, glyph: "governor", label: "GOVERNOR", mapsTo: "king safety", confidence: "presumed" },
      { n: 2, glyph: "boiler", label: "BOILER", mapsTo: "the plant still running", confidence: "presumed" },
      { n: 3, glyph: "belt", label: "BELT", mapsTo: "proofs coupled to the shaft", confidence: "presumed" },
      { n: 4, glyph: "valve", label: "VALVE", mapsTo: "throttle before the break", confidence: "presumed" },
      { n: 5, glyph: "gauge", label: "GAUGE", mapsTo: "92.5% coverage", confidence: "confirmed" },
      { n: 6, glyph: "key", label: "KEY", mapsTo: "role-based access", confidence: "confirmed" },
      { n: 7, glyph: "gauge", label: "GAUGE", mapsTo: "99.9% uptime", confidence: "confirmed" },
      { n: 8, glyph: "ledger", label: "LEDGER", mapsTo: "the reliability proofs", confidence: "confirmed" },
    ],
    numerals: [
      { mark: "1", x: 47.0, y: 6.0, fromX: 49.2, fromY: 13.4, glyph: "governor" },
      { mark: "1a", x: 37.0, y: 8.0, fromX: 37.5, fromY: 22.3, glyph: "governor" },
      { mark: "1b", x: 57.0, y: 6.0, fromX: 58.0, fromY: 33.1, glyph: "governor" },
      { mark: "1c", x: 91.0, y: 8.0, fromX: 86.0, fromY: 13.7, glyph: "governor" },
      { mark: "2", x: 7.0, y: 48.0, fromX: 15.7, fromY: 51.9, glyph: "boiler" },
      { mark: "2a", x: 5.0, y: 16.0, fromX: 11.8, fromY: 16.0, glyph: "boiler" },
      { mark: "3", x: 33.0, y: 92.0, fromX: 34.0, fromY: 63.0, glyph: "belt" },
      { mark: "4", x: 65.0, y: 92.0, fromX: 66.0, fromY: 70.7, glyph: "valve" },
      { mark: "5", x: 93.0, y: 42.0, fromX: 84.6, fromY: 42.0, glyph: "gauge" },
      { mark: "6", x: 93.0, y: 62.0, fromX: 88.0, fromY: 67.7, glyph: "key" },
      { mark: "7", x: 93.0, y: 54.0, fromX: 84.3, fromY: 55.9, glyph: "gauge" },
      { mark: "8", x: 95.0, y: 76.0, fromX: 84.4, fromY: 85.7, glyph: "ledger" },
    ],
    figLabels: [
      { n: 1, x: 3, y: 64 },
      { n: 2, x: 72, y: 4, caption: "vertical section of the flyball head" },
    ],
    detail: { title: "vertical section of the flyball head" },
  },
} as const satisfies Record<string, ApparatusSpec>;

export const VERIDIAN_PRESS: ApparatusSpec = {
  fig: 6,
  move: "5. d4",
  function: "PRINTING THE MORNING EDITION",
  filed: "Apr. 2026",
  viewBox: SHEET,
  layout: "elevation",
  flow: [1, 2, 3, 4, 5, 6, 7],
  engraving: {
    src: "/figures/fig-d4.webp",
    ...ENGRAVING,
    alt: "Patent-style engraving: a morning press in numbered parts — hopper, composing room, stereotype, roller, belt, and edition.",
  },
  review: {
    status: "validated",
    notes:
      "Veridian exhibit. Paper stock = infrastructure plans; composing room = graph retrieval; stereotype = distilled model; edition = recommendations. 99.9% uptime is résumé-public.",
  },
  parts: [
    { n: 1, glyph: "hopper", label: "HOPPER", mapsTo: "paper stock — infrastructure plans", confidence: "confirmed" },
    { n: 2, glyph: "funnel", label: "FUNNEL", mapsTo: "the intercept", confidence: "presumed" },
    { n: 3, glyph: "typecase", label: "COMPOSING ROOM", mapsTo: "graph retrieval", confidence: "confirmed" },
    { n: 4, glyph: "mold", label: "STEREOTYPE", mapsTo: "distilled model", confidence: "confirmed" },
    { n: 5, glyph: "roller", label: "ROLLER", mapsTo: "the press", confidence: "presumed" },
    { n: 6, glyph: "belt", label: "BELT", mapsTo: "the run", confidence: "presumed" },
    { n: 7, glyph: "ledger", label: "EDITION", mapsTo: "the morning recommendations", confidence: "confirmed" },
    { n: 8, glyph: "gauge", label: "GAUGE", mapsTo: "99.9% uptime", confidence: "confirmed" },
  ],
  numerals: [
    { mark: "1", x: 7.0, y: 16.0, fromX: 17.6, fromY: 16.0, glyph: "hopper" },
    { mark: "2", x: 7.0, y: 34.0, fromX: 33.1, fromY: 34.0, glyph: "funnel" },
    { mark: "3", x: 5.0, y: 46.0, fromX: 17.2, fromY: 46.0, glyph: "typecase" },
    { mark: "4", x: 57.0, y: 96.0, fromX: 51.1, fromY: 92.6, glyph: "mold" },
    { mark: "5", x: 51.0, y: 8.0, fromX: 51.7, fromY: 28.4, glyph: "roller" },
    { mark: "5a", x: 47.0, y: 18.0, fromX: 52.0, fromY: 34.5, glyph: "roller" },
    { mark: "6", x: 93.0, y: 30.0, fromX: 83.3, fromY: 33.9, glyph: "belt" },
    { mark: "7", x: 97.0, y: 42.0, fromX: 93.2, fromY: 43.1, glyph: "ledger" },
    { mark: "7a", x: 95.0, y: 52.0, fromX: 92.2, fromY: 48.7, glyph: "ledger" },
    { mark: "8", x: 71.0, y: 8.0, fromX: 71.8, fromY: 18.1, glyph: "gauge" },
  ],
  figLabels: [
    { n: 1, x: 3, y: 64 },
    { n: 2, x: 18, y: 96, caption: "the stereotype plate" },
  ],
  detail: { title: "the stereotype plate" },
};
