import { CIRCUITMIND_LINE, MIRRORFI_VAULT, RISK_ENGINE, LEADS_HALL, VERIDIAN_PLANT } from "@/content/project-figures";
import { repoArtifacts, resumeData } from "@/lib/data";
import { METRICS, POSITIONING } from "@/lib/metrics";
import type { OpeningNode } from "@/lib/opening/types";

export const ROOT_ID = "start";
export const FLAGSHIP_ID = "d4";
export const ENGINE_NODE_ID = "start";

function project(slug: string) {
  const p = resumeData.projects.find((x) => x.slug === slug);
  if (!p) throw new Error(`Missing project: ${slug}`);
  return p;
}

const edu = resumeData.education;
const veridian = project("veridian");
const circuit = project("circuitmindai");
const mirrorfi = project("mirrorfi");
const graphrag = project("multi-agent-graphrag");
const risk = project("financial-risk-predictor");
const lead = project("distributed-lead-scorer");
const slm = project("slm-distillation-engine");

const mail = `mailto:${resumeData.email}`;
const github = `https://${resumeData.github}`;
const linkedin = `https://${resumeData.linkedin}`;

/** Period filler for empty column space. Copy lives here, not in the renderer. */
export const BROADSHEET = {
  errataKicker: "Errata",
  errata: "None reported. Corrections to the address above.",
  classifiedKicker: "Situations Wanted",
  classified:
    "Early-career software engineer. Fintech or AI infrastructure. The next line is still to be played.",
  weatherKicker: "Weather",
  weather: "Outlook: shipping",
  stamp: "C50",
  playInvite: "Play the position",
  playHint: "The annotator will respond",
  lampshade: "Annotators and engines have disagreed since 1997.",
  lampshadeLearned: "The learned eval and the annotator have parted on this page.",
  engineBadge: "ENGINE · 2200-anchored · −143 · 50k-node trial",
  settling: "settling…",
  stepPrev: "Previous move",
  stepNext: "Next move",
  weightsPending: "Learned weights still in the post — handcrafted holds the line.",
  weightsError: "The learned packet did not arrive. Refresh, or trust the annotator. — Ed.",
  engineDown: "The engine is thinking about something else. Refresh, or trust the annotator. — Ed.",
  readHintDesktop: "Click any move. ← → steps the mainline, or skip the diagram and read the scoresheet.",
  readHintTouch: "Tap the chevrons under the board, or skip the diagram and read the scoresheet.",
  evaluationsKicker: "The evaluations meet",
  evaluationsHed: "LEARNED FALLS −143 ELO AT 50 000 NODES",
  evaluationsDek:
    "Two evals, one search. Handcrafted PeSTO against the playing 768×2×256 net (nnue-lichess-cc0-768x2x256-32-1-2026-08-29) trained on 20 million quiet CC0 Lichess cloud evals — depth-12 labels, three epochs, hold-out r vs Stockfish 0.64, r vs PeSTO 0.70. LEARNED is the masthead eval; PeSTO remains a comparison toggle and the Gate C opponent. This column is a fixed-N match at 50 000 nodes a move, 100 games, colours swapped on the fifty-opening suite — not a terminated SPRT. 1 win, 59 draws, 40 losses. LLR −2.33 against bounds ±2.94 is inconclusive; the ±40.5 Elo bar is the 95% interval on that fixed sample. Gate A at the same cap was 0.0 Elo (17–66–17, every pair 1–1), so the −143 is not a colour or adjudication artefact. The earlier −100 at 1 000 nodes was the v1 128; do not compare the two caps. The 2200 on the glass is a club-strength anchor, not a CCRL listing.",
  evaluationsSprt:
    "fixed-N: −143.1 ±40.5 Elo @ 50 000 nodes, 100 games, LLR −2.33 (inconclusive; SPRT unterminated)",
  evaluationsHonesty:
    "Honest Elo: the deltas are rigorous, the anchor is declared. A loss at the spec cap is still a result.",
  eloChartKicker: "Elo over commits",
  eloChartCaption:
    "Each point is a match JSON at 50 000 nodes/move. Gate A is handcrafted vs itself: 0.0 Elo, 100 games, every colour-swapped pair 1–1. Gate C is the depth-12 256, fixed-N, below the axis. The v1 128 at 1 000 nodes (−100) is a different regime.",
  closerKicker: "Adjourned",
  closerHed: "The scoresheet stands.",
  closer:
    "The line is the work. The measurement is on the glass. What the next move writes is still to be played. The next line I want to play: measured systems in fintech infrastructure.",
  closerSign: "Anas Tarek Qumhiyeh",
  eloCommits: [
    { commit: "gate-a-50k", label: "A · 50k", elo: 0, games: 100 },
    { commit: "gate-c-50k", label: "C · 256", elo: -143, games: 100 },
  ] as { commit: string; label: string; elo: number; games: number }[],
  gameKicker: "Opening Preparation",
  gameDek: "The portfolio told as a chess game.",
  printEdition: "Print edition",
  printHref: "/print-edition",
  resumeLabel: "Resume",
  issueKicker: "In this issue",
  wayfindLabel: "index",
  skipLink: "Skip to selected work",
  skipExhibit: "Skip to the exhibit",
  skipBoard: "Skip chessboard",
  exploreCareer: "Explore career story",
  pauseGame: "Pause",
  howToRead: "The résumé is literal; the chess is annotation.",
  boardKeys: "Arrow keys step the scoresheet. Chevrons under the diagram do the same.",
  boardPlayable: "The board is waiting for a move.",
  boardAutoplay: "Playing the mainline. Pause to stop.",
  backToWork: "Back to selected work",
  copyEmail: "Copy email",
  copiedEmail: "Copied",
  dek: POSITIONING.dek,
  tagline: POSITIONING.tagline,
  availability: POSITIONING.availability,
  graduateNote: POSITIONING.graduateNote,
  puzzleKicker: "Today's puzzle",
  classifiedSticky: "Availability",
  labKicker: "Analysis board",
  labHeading: "Laboratory",
  labDek: "Side lines: the puzzle, the engine trial, and the matches I published anyway.",
  colophonKicker: "How this paper was set",
  colophon:
    "Type: Libre Baskerville, Lora, IBM Plex Mono. Ink #1a120c on cream #f6eedc. Radius none. The tree is the repertoire; the scoresheet is the CV; the glass case is mailbox-64 alpha-beta with LEARNED as the masthead eval — PeSTO remains a comparison toggle. Gate C at 50 000 nodes printed −143.1 ±40.5 Elo, 100 games, LLR −2.33. The 2200 on that case is club strength, not a published Elo. No template. Chess is content, never a lock.",
  colophonHonestyKicker: "Three registers",
  colophonHonesty:
    "Photographs real and composed; impressions imagined; the subject is real throughout.",
  colophonWitnessKicker: "The witnesses",
  colophonWitnesses:
    "Vitest signs the parts list and the node counts. Playwright walks the paper the way a reader would — deep links, the board, the lightbox. The table below is perft: the move generator's receipt against the published start-position series. If those numbers slip, the engine is lying.",
  perftKicker: "Perft — the generator's receipt",
  correctionKicker: "Correction",
  correctionHed: "The page you requested was a misprint.",
  correctionDek: "It never made the plate. The game is still on the front page.",
  homeLink: "Back to the game",
  searching: "going to press…",
  pressMark: "Set by hand. No template survived.",
  weatherCycle: ["Outlook: shipping", "Fog on the e-file", "High pressure on d4"],
};

/**
 * The opening tree. Adding or editing a node happens only here.
 * Renderers (tree, notation, board, panel) never hardcode ids or copy.
 *
 * House style (casing): Title Case for chapter titles; ALL CAPS for headlines;
 * small caps for kickers; sentence case for facts. Compact numbers in facts
 * ("100M events/day"); words-style only in annotations.
 */
export const OPENING_NODES: OpeningNode[] = [
  {
    id: "start",
    type: "mainline",
    parent: null,
    fig: "♔",
    san: "—",
    moveNumber: 0,
    color: null,
    sym: "",
    label: "Starting position",
    kind: "Start",
    title: "Opening Preparation",
    scanTitle: `${resumeData.name} — ${POSITIONING.identity}`,
    fact: `${resumeData.name}. ${POSITIONING.dek} ${POSITIONING.tagline} ${edu.school}, graduated ${edu.graduation}.`,
    commentary:
      "The board is set before the first pawn moves. What follows is not a puzzle. It is the line I actually played, in a game I've played since I was a teenager — jobs as moves, annotations as voice. Chess is the content, never the lock.",
    eval: 0.2,
    evalText: "+0.2",
    artifacts: [],
    plies: [],
    hl: null,
    cap: "Starting position",
  },
  {
    id: "e4",
    type: "mainline",
    parent: "start",
    fig: "♙",
    san: "e4",
    moveNumber: 1,
    color: "w",
    sym: "!",
    label: "The University Opening",
    kind: "Education",
    title: "The University Opening",
    scanTitle: `Monash University — ${edu.degree}`,
    fact: `${edu.degree}, ${edu.honours}. ${edu.school}, ${edu.location}. Graduated ${edu.graduation}. WAM ${edu.wam}, CGPA ${edu.cgpa}.`,
    commentary:
      "Every open game starts by occupying the centre. I opened with software engineering — not because it was the only file, but because it was the one that let both bishops out.",
    eval: 0.35,
    evalText: "+0.35",
    artifacts: [],
    plies: [{ from: "e2", to: "e4" }],
    hl: ["e2", "e4"],
    cap: "Position after 1. e4",
    inlineDiagram: true,
    clipping: {
      kicker: "University Intelligence",
      headline: "HONOURS FOR MONASH ENGINEERING GRADUATE",
      dateline: "Bandar Sunway, May 2026.",
      src: "/plates/clip-sunway.jpg",
      caption: "On the cloister — file photo.",
      alt: "Halftone photograph: the cloister at Monash Malaysia, stone arches and a walk in shade.",
    },
  },
  {
    id: "alekhine",
    type: "variation",
    parent: "e4",
    fig: "♞",
    san: "Nf6",
    moveNumber: 1,
    color: "b",
    sym: "!?",
    label: "The ML Defence",
    kind: "Project",
    title: "The ML Defence",
    fact: `${risk.name} — ${risk.subtitle}. LightGBM / XGBoost, ${METRICS.riskAuc.display} (${METRICS.riskAuc.vs}). SHAP for the why. BentoML to a REST API. Daily retrain on Kafka.`,
    commentary:
      "I built models that had to be interpreted, deployed, and retrained every morning — not fitted once for a screenshot. The knight invites the centre forward: the ML line rather than the systems line.",
    eval: 0.25,
    evalText: "!?",
    artifacts: [
      { label: risk.name, href: `/projects/${risk.slug}` },
      ...repoArtifacts(risk.github, risk.name),
    ],
    plate: {
      src: "/plates/plate-risk.jpg",
      caption: "Plate · Financial Risk Predictor — the ledger, not the slogan.",
      alt: "Halftone photograph: an open ledger with ruled columns, a pen resting on the page.",
    },
    figure: RISK_ENGINE,
    plies: [{ from: "g8", to: "f6" }],
    hl: ["g8", "f6"],
    cap: "Position after 1…Nf6 (Alekhine’s Defence)",
  },
  {
    id: "e5",
    type: "mainline",
    parent: "e4",
    fig: "♟",
    san: "e5",
    moveNumber: 1,
    color: "b",
    sym: "",
    label: "Meeting e4 with e5",
    kind: "Identity",
    title: "Meeting e4 with e5",
    scanTitle: POSITIONING.identity,
    fact: `${resumeData.name}. ${POSITIONING.dek} ${POSITIONING.tagline}`,
    commentary:
      "The classical answer. I did not decline into a closed system. Product engineering on one wing, the data path on the other.",
    eval: 0.3,
    evalText: "+0.30",
    artifacts: [],
    plies: [{ from: "e7", to: "e5" }],
    hl: ["e7", "e5"],
    cap: "Position after 1…e5",
  },
  {
    id: "nf3",
    type: "mainline",
    parent: "e5",
    fig: "♘",
    san: "Nf3",
    moveNumber: 2,
    color: "w",
    sym: "",
    label: "First Developed Piece",
    kind: "Internship",
    title: "First Developed Piece",
    scanTitle: "Petronas — Project Engineer Intern",
    fact: "Petronas — Project Engineer Intern, Nov 2024 – Feb 2025. Converted paid MATLAB licences into free Python packages, then wrote the tests that proved it. Presented usability findings to department leadership.",
    commentary:
      "Knights before bishops, they say. Petronas was the first industry square — converting paid MATLAB licences into free Python packages, then writing the tests that proved it.",
    eval: 0.4,
    evalText: "+0.40",
    artifacts: [],
    plies: [{ from: "g1", to: "f3" }],
    hl: ["g1", "f3"],
    cap: "Position after 2. Nf3",
    clipping: {
      kicker: "Engineering Notes",
      headline: "PETRONAS RETAINS YOUNG TALENT ON THE PIPELINE DESIGN TEAM",
      dateline: "Kuala Lumpur, Nov. 2024.",
      src: "/plates/clip-petronas.jpg",
      caption: "Before the towers — file photo.",
      alt: "Halftone photograph: the Petronas Towers seen from the street, two figures in the foreground.",
      inset: {
        src: "/plates/clip-petronas-inset.jpg",
        caption: "The pipeline elevation — file photo.",
        alt: "Halftone photograph: a pipeline elevation drawing, labelled stations along the run.",
      },
    },
  },
  {
    id: "elephant",
    type: "variation",
    parent: "nf3",
    fig: "♟",
    san: "d5",
    moveNumber: 2,
    color: "b",
    sym: "!",
    label: "The Elephant Gambit",
    kind: "Project",
    title: "The Elephant Gambit",
    fact: `${lead.name} — ${lead.subtitle}. PySpark over ${METRICS.leadThroughput.display}, Deep Interest Network on PyTorch DDP, checkpointed so a multi-hour run could not lose the tape.`,
    commentary:
      "A hundred million events a day had to keep moving even when a job died mid-run. 2…d5 is that impatience, with the checkpoint so the sacrifice is not a bluff.",
    eval: 0.45,
    evalText: "+0.45",
    artifacts: [
      { label: lead.name, href: `/projects/${lead.slug}` },
      ...repoArtifacts(lead.github, lead.name),
    ],
    plate: {
      src: "/plates/plate-leads.jpg",
      caption: "Plate · Distributed Lead Scorer — the sorting hall at full tilt.",
      alt: "Halftone photograph: a mail-sorting hall, pigeonholes stretching into the distance.",
    },
    figure: LEADS_HALL,
    plies: [{ from: "d7", to: "d5" }],
    hl: ["d7", "d5"],
    cap: "Position after 2…d5 (Elephant Gambit)",
  },
  {
    id: "philidor",
    type: "not-taken",
    parent: "nf3",
    fig: "♟",
    san: "d6",
    moveNumber: 2,
    color: "b",
    sym: "?!",
    label: "The Philidor, Declined",
    kind: "Road not taken",
    title: "The Philidor, Declined",
    fact: "After Petronas the MATLAB world was still there — MathCAD, department code, a quieter engineering path with licences already paid.",
    commentary:
      "2…d6 keeps the position closed. I developed the knight instead. The dashed line is honest: I could have stayed in the MATLAB world, licences already paid, MathCAD glowing on a CRT. The other life stays on the page as a ghost — visible, declined, and not a regret. I did not stay.",
    eval: -0.55,
    evalText: "?!",
    artifacts: [],
    plies: [{ from: "d7", to: "d6" }],
    hl: ["d7", "d6"],
    cap: "Position after 2…d6 (Philidor, declined)",
    impression: {
      src: "/plates/impression-philidor.jpg",
      caption:
        "The engineer as he might have been found — MathCAD open, licences already paid. An artist's impression.",
      alt: "Artist's impression: an engineer at a CRT, MathCAD open, a quieter lab than the one he chose.",
    },
  },
  {
    id: "nc6",
    type: "mainline",
    parent: "nf3",
    fig: "♞",
    san: "Nc6",
    moveNumber: 2,
    color: "b",
    sym: "",
    label: "Defending the Pawn",
    kind: "Internship",
    title: "Defending the Pawn",
    scanTitle: "Setel — Software Engineer Intern",
    fact: `Setel — Software Engineer Intern, Jul 2025 – Dec 2025. Payment engine: authorization and capture. ${METRICS.setelCoverage.display}, ${METRICS.setelDefects.display}.`,
    commentary:
      "Payment-engine defects used to ship as far as the pump. I sat on that square and made sure the pawn could not be taken for free.",
    eval: 0.35,
    evalText: "+0.35",
    artifacts: [],
    plies: [{ from: "b8", to: "c6" }],
    hl: ["b8", "c6"],
    cap: "Position after 2…Nc6",
    clipping: {
      kicker: "Commercial Intelligence",
      headline: "SETEL RECRUITS NEW HANDS ON THE PAYMENT ENGINE",
      dateline: "Kuala Lumpur, Jul. 2025.",
      src: "/plates/clip-setel.jpg",
      caption: "At the pump — file photo.",
      alt: "Halftone photograph: a fuel pump at night, the brand lit, a car at the island.",
    },
  },
  {
    id: "bc4",
    type: "mainline",
    parent: "nc6",
    fig: "♗",
    san: "Bc4",
    moveNumber: 3,
    color: "w",
    sym: "",
    label: "Pointing at f7",
    kind: "Contract",
    title: "Pointing at f7",
    scanTitle: "Western Digital — Full-stack Engineer",
    fact: `Western Digital — Full-stack Engineer, Feb 2025 – Dec 2025. Lab-systems dashboard; role-based access for 50+ staff, ${METRICS.wdOversight.display}. WebSocket to the lab's deep-learning model; shortest path between stations in under 100 ms.`,
    commentary:
      "The Italian bishop looks at the weakest point in the castled position. At WD the weakness was watching lab systems by hand. I put a bishop there.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [],
    plies: [{ from: "f1", to: "c4" }],
    hl: ["f1", "c4"],
    cap: "Position after 3. Bc4",
    clipping: {
      kicker: "Laboratory Notes",
      headline: "WESTERN DIGITAL ADDS NEW HANDS ON THE LAB FLOOR",
      dateline: "Feb. 2025.",
      src: "/plates/clip-wd.jpg",
      caption: "On the lab floor — file photo.",
      alt: "Halftone photograph: a lab bench with racks and monitors, a figure at the near station.",
    },
  },
  {
    id: "bc5",
    type: "mainline",
    parent: "bc4",
    fig: "♝",
    san: "Bc5",
    moveNumber: 3,
    color: "b",
    sym: "",
    label: "Quiet Italian",
    kind: "Project",
    title: "Quiet Italian",
    scanTitle: "CircuitMindAI — PCB inspection",
    fact: `${circuit.name} — ${circuit.subtitle}. Amazon Nova Pro for vision, Nova Sonic for voice. Next.js and Express, CI/CD to ECS Fargate, edge cache for when the network drops.`,
    commentary:
      "CircuitMind sees faults in the copper and talks back over a live voice channel. Black develops the same way — vision on the board, voice on the file.",
    eval: 0.45,
    evalText: "+0.45",
    artifacts: [
      { label: circuit.name, href: `/projects/${circuit.slug}` },
      ...repoArtifacts(circuit.github, circuit.name),
    ],
    plate: {
      src: "/plates/plate-circuitmind.jpg",
      caption: "Plate · CircuitMindAI — copper under the loupe.",
      alt: "Halftone photograph: a printed circuit board under a loupe, traces filling the frame.",
    },
    figure: CIRCUITMIND_LINE,
    plies: [{ from: "f8", to: "c5" }],
    hl: ["f8", "c5"],
    cap: "Position after 3…Bc5",
  },
  {
    id: "oo",
    type: "mainline",
    parent: "bc5",
    fig: "♔",
    san: "O-O",
    moveNumber: 4,
    color: "w",
    sym: "!",
    label: "Castling",
    kind: "Practice",
    title: "Castling",
    fact: `Reliability before the break: Setel ${METRICS.setelCoverage.value} coverage; WD role-based access; Veridian ${METRICS.veridianUptime.display}.`,
    commentary:
      "Castling is not a retreat. It is the move that says king safety before the central break. I ship the same way — tests and access control before the spectacular sacrifice.",
    eval: 0.55,
    evalText: "+0.55",
    artifacts: [{ label: veridian.name, href: `/projects/${veridian.slug}` }],
    plies: [
      { from: "e1", to: "g1" },
      { from: "h1", to: "f1" },
    ],
    hl: ["e1", "g1"],
    cap: "Position after 4. O-O",
    inlineDiagram: true,
  },
  {
    id: "nf6",
    type: "mainline",
    parent: "oo",
    fig: "♞",
    san: "Nf6",
    moveNumber: 4,
    color: "b",
    sym: "!",
    label: "The Knight Comes In",
    kind: "Project",
    title: "The Knight Comes In",
    fact: `${mirrorfi.name} — Grand Prize, Solana Megahack 2025. No-code vault strategies across Drift, Jupiter, and Meteora; shareable MongoDB schemas; auto-rebalancing on live APY.`,
    commentary:
      "Grand prize is a symbol. The work was a product: shareable vault lines, a schema people could copy. Then the last minor piece develops.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [
      { label: mirrorfi.name, href: `/projects/${mirrorfi.slug}` },
      ...repoArtifacts(mirrorfi.github, mirrorfi.name),
    ],
    plate: {
      src: "/plates/plate-mirrorfi.jpg",
      caption: "Plate · MirrorFi — the vault wall.",
      alt: "Halftone photograph: a vault door and lock-work, lit like a bank interior.",
    },
    figure: MIRRORFI_VAULT,
    plies: [{ from: "g8", to: "f6" }],
    hl: ["g8", "f6"],
    cap: "Position after 4…Nf6",
    puzzle: {
      prompt: "White to move — find the break.",
      target: "d4",
      hit: "!! — found over the board.",
      miss: "A developing move. The break was d4. — Ed.",
    },
  },
  {
    id: "d4",
    type: "mainline",
    parent: "nf6",
    fig: "♙",
    san: "d4",
    moveNumber: 5,
    color: "w",
    sym: "!!",
    label: "The Central Break",
    kind: "Flagship",
    title: "The Central Break",
    scanTitle: "Veridian — MLOps Tradeoff Engine",
    fact: `${veridian.name} — ${veridian.subtitle}: intercepts Terraform and Kubernetes and recommends lower-carbon hardware. At Monash: GraphRAG over university regulations, self-correcting Text-to-Cypher, ${METRICS.monashRetrieval.display}; an SLM distilled from that reasoning, ${METRICS.slmLatency.value} latency.`,
    commentary:
      "You castle, then you break the centre. d4 is the move this scoresheet hangs on: agents that intercept infrastructure, a graph that actually understands prerequisites, measurements instead of demos. The double-exclaim is Informant’s, not mine — but I played it.",
    eval: 1.6,
    evalText: "!!",
    artifacts: [
      { label: veridian.name, href: `/projects/${veridian.slug}` },
      { label: graphrag.name, href: `/projects/${graphrag.slug}` },
      { label: slm.name, href: `/projects/${slm.slug}` },
    ],
    plate: {
      src: "/plates/plate-veridian.jpg",
      caption: "Plate · Veridian — the central break, intercepted as infrastructure.",
      alt: "Halftone photograph: an engineer at a drafting table, an infrastructure drawing unrolled before him.",
    },
    figure: VERIDIAN_PLANT,
    plies: [{ from: "d2", to: "d4" }],
    hl: ["d2", "d4"],
    cap: "Position after 5. d4",
    inlineDiagram: true,
  },
  {
    id: "closed",
    type: "variation",
    parent: "d4",
    fig: "♟",
    san: "d6",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "The Closed Centre",
    kind: "Project",
    title: "The Closed Centre",
    scanTitle: "Multi-Agent GraphRAG — policy-corpus retrieval",
    fact: `${graphrag.name} — ${graphrag.subtitle}. ${METRICS.graphragRetrieval.method} on the university's policy corpus. ${METRICS.graphragRetrieval.display}.`,
    commentary:
      "Prerequisites and credit-transfer live as edges, not another embedding dump. Black can refuse the capture and keep the centre closed — the graph is that kind of patience.",
    eval: 0.55,
    evalText: "+0.55",
    artifacts: [
      { label: graphrag.name, href: `/projects/${graphrag.slug}` },
      ...repoArtifacts(graphrag.github, graphrag.name),
    ],
    plate: {
      src: "/plates/plate-graphrag.jpg",
      caption: "Plate · Multi-Agent GraphRAG — the card catalog, not the slogan.",
      alt: "Halftone photograph: wooden card-catalog drawers, one drawer open on a labelled card.",
    },
    plies: [{ from: "d7", to: "d6" }],
    hl: ["d7", "d6"],
    cap: "Position after 5…d6 (Closed Centre)",
  },
  {
    id: "bb6",
    type: "variation",
    parent: "d4",
    fig: "♝",
    san: "Bb6",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "Tucking the Bishop",
    kind: "Project",
    title: "Tucking the Bishop",
    fact: `${slm.name} — ${slm.subtitle}. 70B teacher into a 3B student via QLoRA; DeepSpeed and FlashAttention so the distillation fit; ${METRICS.slmLatency.display}, ${METRICS.slmInference.display}.`,
    commentary:
      "Distillation keeps the same job on a smaller piece, cheaper to keep on the board. The Italian bishop steps back to b6 and still looks at the same diagonal.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [
      { label: slm.name, href: `/projects/${slm.slug}` },
      ...repoArtifacts(slm.github, slm.name),
    ],
    plate: {
      src: "/plates/plate-slm.jpg",
      caption: "Plate · SLM Distillation — teacher and student on the same file.",
      alt: "Halftone photograph: two machines side by side, the smaller one cabled to the larger.",
    },
    plies: [{ from: "c5", to: "b6" }],
    hl: ["c5", "b6"],
    cap: "Position after 5…Bb6 (tucking the bishop)",
  },
  {
    id: "exd4",
    type: "mainline",
    parent: "d4",
    fig: "♟",
    san: "exd4",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "Taking on d4",
    kind: "Method",
    title: "Taking on d4",
    fact: `Named results that had to survive the demo: Veridian ${METRICS.veridianUptime.display} (${METRICS.veridianEmissions.display}); Monash GraphRAG ${METRICS.monashRetrieval.display}; Western Digital ${METRICS.wdOversight.display}; Financial Risk Predictor ${METRICS.riskAuc.display}; SLM Distillation ${METRICS.slmInference.display}; Lead Scorer ${METRICS.leadThroughput.display}.`,
    commentary:
      "I would rather show the graph than the slogan. Accepting the pawn is accepting that the numbers have owners.",
    eval: 0.7,
    evalText: "+0.70",
    artifacts: [{ label: slm.name, href: `/projects/${slm.slug}` }],
    plies: [{ from: "e5", to: "d4" }],
    hl: ["e5", "d4"],
    cap: "Position after 5…exd4",
  },
  {
    id: "re1",
    type: "mainline",
    parent: "exd4",
    fig: "♖",
    san: "Re1",
    moveNumber: 6,
    color: "w",
    sym: "",
    label: "The Open File",
    kind: "Outlook",
    title: "The Open File",
    scanTitle: "Next: measured systems in fintech infrastructure",
    fact: `${resumeData.name}. The next line I want to play: measured systems in fintech infrastructure.`,
    commentary:
      "I want the next line to be measured systems in fintech infrastructure — on the open file. Rooks belong where the work already points.",
    eval: 0.8,
    evalText: "+0.80",
    artifacts: [
      { label: "Email", href: mail },
      { label: "GitHub", href: github },
      { label: "LinkedIn", href: linkedin },
      { label: BROADSHEET.resumeLabel, href: BROADSHEET.printHref },
    ],
    plies: [{ from: "f1", to: "e1" }],
    hl: ["f1", "e1"],
    cap: "Position after 6. Re1",
  },
];
