import { CIRCUITMIND_LINE, MIRRORFI_VAULT, RISK_ENGINE, LEADS_HALL, VERIDIAN_PLANT } from "@/content/project-figures";
import { resumeData } from "@/lib/data";
import type { OpeningNode } from "@/lib/opening/types";

export const ROOT_ID = "start";
export const FLAGSHIP_ID = "d4";
export const ENGINE_NODE_ID = "start";

function project(slug: string) {
  const p = resumeData.projects.find((x) => x.slug === slug);
  if (!p) throw new Error(`Missing project: ${slug}`);
  return p;
}

const edu = resumeData.education;
const veridian = project("veridian");
const circuit = project("circuitmindai");
const mirrorfi = project("mirrorfi");
const graphrag = project("multi-agent-graphrag");
const risk = project("financial-risk-predictor");
const lead = project("distributed-lead-scorer");
const slm = project("slm-distillation-engine");

const mail = `mailto:${resumeData.email}`;
const github = `https://${resumeData.github}`;
const linkedin = `https://${resumeData.linkedin}`;

/** Period filler for empty column space. Copy lives here, not in the renderer. */
export const BROADSHEET = {
  errataKicker: "Errata",
  errata: "None reported. Corrections to the address above.",
  classifiedKicker: "Situations Wanted",
  classified:
    "Engineer, MLOps & full-stack, seeks fintech/AI infrastructure post. Apply within →",
  weatherKicker: "Weather",
  weather: "Outlook: shipping",
  stamp: "C50",
  playInvite: "Play the position",
  playHint: "The annotator will respond",
  lampshade: "Annotators and engines have disagreed since 1997.",
  gameKicker: "The game",
  printEdition: "Print edition",
  printHref: "/print-edition",
  issueKicker: "In this issue",
  skipLink: "Skip to the game",
  dek: "Software Engineer — MLOps & Full-Stack",
  availability: "Open to 1–3 year fintech and AI infrastructure roles. Replies within two days.",
  puzzleKicker: "Today's puzzle",
  classifiedSticky: "Situations Wanted — apply within",
  colophonKicker: "How this paper was set",
  colophon:
    "Type: Libre Baskerville, Lora, IBM Plex Mono. Ink #1a120c on cream #f6eedc. Radius none. The tree is the repertoire; the scoresheet is the CV; the glass case is mailbox-64 alpha-beta with PeSTO tables. The 2200 on the masthead of that case is club strength, not a published Elo. No template. Chess is content, never a lock.",
  colophonHonestyKicker: "Three registers",
  colophonHonesty:
    "Photographs real and composed; impressions imagined; the subject is real throughout.",
  colophonWitnessKicker: "The witnesses",
  colophonWitnesses:
    "Vitest signs the parts list and the node counts. Playwright walks the paper the way a reader would — deep links, the board, the lightbox. The table below is perft: the move generator's receipt against the published start-position series. If those numbers slip, the engine is lying.",
  perftKicker: "Perft — the generator's receipt",
  correctionKicker: "Correction",
  correctionHed: "The page you requested was a misprint.",
  correctionDek: "It never made the plate. The game is still on the front page.",
  homeLink: "Back to the game",
  searching: "going to press…",
  pressMark: "Set by hand. No template survived.",
  weatherCycle: ["Outlook: shipping", "Fog on the e-file", "High pressure on d4"],
};

/**
 * The opening tree. Adding or editing a node happens only here.
 * Renderers (tree, notation, board, panel) never hardcode ids or copy.
 */
export const OPENING_NODES: OpeningNode[] = [
  {
    id: "start",
    type: "mainline",
    parent: null,
    fig: "♔",
    san: "—",
    moveNumber: 0,
    color: null,
    sym: "",
    label: "Starting position",
    kind: "Start",
    title: "Opening Preparation",
    fact: `${resumeData.name}. ${resumeData.headline}. ${edu.school}, graduating ${edu.graduation}. Seeking ${resumeData.targetRoles}`,
    commentary:
      "The board is set before the first pawn moves. What follows is not a puzzle. It is the line I actually played, in a game I've played since I was a teenager — jobs as moves, annotations as voice. Step with the arrow keys, or skip the diagram and read the scoresheet. Chess is the content, never the lock.",
    eval: 0.2,
    evalText: "+0.2",
    artifacts: [],
    plies: [],
    hl: null,
    cap: "Starting position",
  },
  {
    id: "e4",
    type: "mainline",
    parent: "start",
    fig: "♙",
    san: "e4",
    moveNumber: 1,
    color: "w",
    sym: "!",
    label: "The University Opening",
    kind: "Education",
    title: "The University Opening",
    fact: `${edu.degree}. ${edu.school}, ${edu.location}. ${edu.graduation}. WAM ${edu.wam}, CGPA ${edu.cgpa}.`,
    commentary:
      "Every open game starts by occupying the centre. I opened with software engineering — not because it was the only file, but because it was the one that let both bishops out.",
    eval: 0.35,
    evalText: "+0.35",
    artifacts: [],
    plies: [{ from: "e2", to: "e4" }],
    hl: ["e2", "e4"],
    cap: "Position after 1. e4",
    inlineDiagram: true,
    clipping: {
      kicker: "University Intelligence",
      headline: "HONOURS FOR ASPIRING MONASH ENGINEERING CANDIDATE",
      dateline: "Bandar Sunway, May 2026.",
      src: "/plates/clip-sunway.jpg",
      caption: "On the cloister — file photo.",
    },
  },
  {
    id: "alekhine",
    type: "variation",
    parent: "e4",
    fig: "♞",
    san: "Nf6",
    moveNumber: 1,
    color: "b",
    sym: "!?",
    label: "The ML Defence",
    kind: "Project",
    title: "The ML Defence",
    fact: `${risk.name} — ${risk.subtitle}. LightGBM / XGBoost, 0.87 AUC-ROC (15% over baseline). SHAP for the why. BentoML to a REST API. Daily retrain on Kafka.`,
    commentary:
      "Not the symmetrical pawn. A knight that invites the centre forward — the ML line rather than the systems line. I played it: models that had to be interpreted, deployed, and retrained every morning, not just fitted once for a screenshot.",
    eval: 0.25,
    evalText: "!?",
    artifacts: [
      { label: risk.name, href: `/projects/${risk.slug}` },
      { label: "Repository", href: risk.github },
    ],
    plate: {
      src: "/plates/plate-risk.jpg",
      caption: "Plate · Financial Risk Predictor — the ledger, not the slogan.",
    },
    figure: RISK_ENGINE,
    plies: [{ from: "g8", to: "f6" }],
    hl: ["g8", "f6"],
    cap: "Position after 1…Nf6 (Alekhine’s Defence)",
  },
  {
    id: "e5",
    type: "mainline",
    parent: "e4",
    fig: "♟",
    san: "e5",
    moveNumber: 1,
    color: "b",
    sym: "",
    label: "Meeting e4 with e5",
    kind: "Identity",
    title: "Meeting e4 with e5",
    fact: `${resumeData.headline}. Target: ${resumeData.targetRoles}`,
    commentary:
      "The classical answer. I did not decline into a closed system. Full-stack plus MLOps is symmetrical development: product on one wing, the data path on the other.",
    eval: 0.3,
    evalText: "+0.30",
    artifacts: [],
    plies: [{ from: "e7", to: "e5" }],
    hl: ["e7", "e5"],
    cap: "Position after 1…e5",
  },
  {
    id: "nf3",
    type: "mainline",
    parent: "e5",
    fig: "♘",
    san: "Nf3",
    moveNumber: 2,
    color: "w",
    sym: "",
    label: "First Developed Piece",
    kind: "Internship",
    title: "First Developed Piece",
    fact: "Project Engineer Intern, Petronas, Nov 2024 – Feb 2025. MATLAB → Python overhaul. −20% department cost, +30% application efficiency. Test cases into production; UX notes to leadership.",
    commentary:
      "Knights before bishops, they say. Petronas was the first industry square — converting paid MATLAB licenses into free Python packages, then writing the tests that proved it.",
    eval: 0.4,
    evalText: "+0.40",
    artifacts: [],
    plies: [{ from: "g1", to: "f3" }],
    hl: ["g1", "f3"],
    cap: "Position after 2. Nf3",
    clipping: {
      kicker: "Engineering Notes",
      headline: "PETRONAS RETAINS YOUNG TALENT ON THE PIPELINE DESIGN TEAM",
      dateline: "Kuala Lumpur, Nov. 2024.",
      src: "/plates/clip-petronas.jpg",
      caption: "Before the towers — file photo.",
      inset: {
        src: "/plates/clip-petronas-inset.jpg",
        caption: "The pipeline elevation — file photo.",
      },
    },
  },
  {
    id: "elephant",
    type: "variation",
    parent: "nf3",
    fig: "♟",
    san: "d5",
    moveNumber: 2,
    color: "b",
    sym: "!",
    label: "The Elephant Gambit",
    kind: "Project",
    title: "The Elephant Gambit",
    fact: `${lead.name} — ${lead.subtitle}. PySpark over 100M+ daily events, Deep Interest Network on PyTorch DDP, checkpointed so a multi-hour run could not lose the tape.`,
    commentary:
      "2…d5 is the impatient move: strike the centre before the pieces are all out. A hundred million events a day is that kind of impatience, with fault-tolerance so the sacrifice is not a bluff.",
    eval: 0.45,
    evalText: "+0.45",
    artifacts: [
      { label: lead.name, href: `/projects/${lead.slug}` },
      { label: "Repository", href: lead.github },
    ],
    plate: {
      src: "/plates/plate-leads.jpg",
      caption: "Plate · Distributed Lead Scorer — the sorting hall at full tilt.",
    },
    figure: LEADS_HALL,
    plies: [{ from: "d7", to: "d5" }],
    hl: ["d7", "d5"],
    cap: "Position after 2…d5 (Elephant Gambit)",
  },
  {
    id: "philidor",
    type: "not-taken",
    parent: "nf3",
    fig: "♟",
    san: "d6",
    moveNumber: 2,
    color: "b",
    sym: "?!",
    label: "The Philidor, Declined",
    kind: "Road not taken",
    title: "The Philidor, Declined",
    fact: "After Petronas the MATLAB world was still there — MathCAD, department code, a quieter engineering path with licenses already paid.",
    commentary:
      "2…d6 keeps the position closed. I developed the knight instead. The dashed line is honest: I could have stayed in the MATLAB world, licenses already paid, MathCAD glowing on a CRT. I did not.",
    eval: -0.55,
    evalText: "?!",
    artifacts: [],
    plies: [{ from: "d7", to: "d6" }],
    hl: ["d7", "d6"],
    cap: "Position after 2…d6 (Philidor, declined)",
    impression: {
      src: "/plates/impression-philidor.jpg",
      caption:
        "The engineer as he might have been found — MathCAD open, licenses already paid. An artist's impression.",
    },
  },
  {
    id: "nc6",
    type: "mainline",
    parent: "nf3",
    fig: "♞",
    san: "Nc6",
    moveNumber: 2,
    color: "b",
    sym: "",
    label: "Defending the Pawn",
    kind: "Internship",
    title: "Defending the Pawn",
    fact: "Software Engineer Intern, Setel, Jul 2025 – Dec 2025. Payment engine: authorization and capture. 92.5% unit-test coverage, −40% production defects, −30% onboarding time via documentation.",
    commentary:
      "e5 is the payment engine. If it falls, the opening collapses. I sat on that square and made sure the pawn could not be taken for free.",
    eval: 0.35,
    evalText: "+0.35",
    artifacts: [],
    plies: [{ from: "b8", to: "c6" }],
    hl: ["b8", "c6"],
    cap: "Position after 2…Nc6",
    clipping: {
      kicker: "Commercial Intelligence",
      headline: "SETEL RECRUITS NEW HANDS ON THE PAYMENT ENGINE",
      dateline: "Kuala Lumpur, Jul. 2025.",
      src: "/plates/clip-setel.jpg",
      caption: "At the pump — file photo.",
    },
  },
  {
    id: "bc4",
    type: "mainline",
    parent: "nc6",
    fig: "♗",
    san: "Bc4",
    moveNumber: 3,
    color: "w",
    sym: "",
    label: "Pointing at f7",
    kind: "Contract",
    title: "Pointing at f7",
    fact: "Full Stack Engineer, Western Digital, Feb 2025 – Dec 2025. Lab-systems dashboard; RBAC (admin, user, superuser) for 50+ people; −40% manual oversight. WebSocket to the DL model; pathing in under 100 ms.",
    commentary:
      "The Italian bishop looks at the weakest point in the castled position. At WD the weakness was watching lab systems by hand. I put a bishop there.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [],
    plies: [{ from: "f1", to: "c4" }],
    hl: ["f1", "c4"],
    cap: "Position after 3. Bc4",
    clipping: {
      kicker: "Laboratory Notes",
      headline: "WESTERN DIGITAL NEWEST ADDITION FOR THE LAB FLOOR",
      dateline: "Feb. 2025.",
      src: "/plates/clip-wd.jpg",
      caption: "On the lab floor — file photo.",
    },
  },
  {
    id: "bc5",
    type: "mainline",
    parent: "bc4",
    fig: "♝",
    san: "Bc5",
    moveNumber: 3,
    color: "b",
    sym: "",
    label: "Quiet Italian",
    kind: "Project",
    title: "Quiet Italian",
    fact: `${circuit.name} — ${circuit.subtitle}. Amazon Nova Pro for vision, Nova Sonic for voice. Next.js and Express, CI/CD to ECS Fargate, edge cache for when the network drops.`,
    commentary:
      "Black develops the same way. Vision on the board, voice on the file. Both sides looking at faults in the copper.",
    eval: 0.45,
    evalText: "+0.45",
    artifacts: [
      { label: circuit.name, href: `/projects/${circuit.slug}` },
      { label: "Repository", href: circuit.github },
    ],
    plate: {
      src: "/plates/plate-circuitmind.jpg",
      caption: "Plate · CircuitMindAI — copper under the loupe.",
    },
    figure: CIRCUITMIND_LINE,
    plies: [{ from: "f8", to: "c5" }],
    hl: ["f8", "c5"],
    cap: "Position after 3…Bc5",
  },
  {
    id: "oo",
    type: "mainline",
    parent: "bc5",
    fig: "♔",
    san: "O-O",
    moveNumber: 4,
    color: "w",
    sym: "!",
    label: "Castling",
    kind: "Practice",
    title: "Castling",
    fact: "Reliability before the break: Setel 92.5% coverage; WD role-based access; Veridian 99.9% uptime.",
    commentary:
      "Castling is not a retreat. It is the move that says king safety before the central break. I ship the same way — tests and access control before the spectacular sacrifice.",
    eval: 0.55,
    evalText: "+0.55",
    artifacts: [{ label: veridian.name, href: `/projects/${veridian.slug}` }],
    plies: [
      { from: "e1", to: "g1" },
      { from: "h1", to: "f1" },
    ],
    hl: ["e1", "g1"],
    cap: "Position after 4. O-O",
    inlineDiagram: true,
  },
  {
    id: "nf6",
    type: "mainline",
    parent: "oo",
    fig: "♞",
    san: "Nf6",
    moveNumber: 4,
    color: "b",
    sym: "!",
    label: "The Knight Comes In",
    kind: "Project",
    title: "The Knight Comes In",
    fact: `${mirrorfi.name} — Grand Prize, Solana Megahack 2025. No-code vault strategies across Drift, Jupiter, and Meteora; shareable MongoDB schemas; auto-rebalancing on live APY.`,
    commentary:
      "The last minor piece. A hackathon that had to look like a product: shareable lines, a schema people could copy. Grand prize is a symbol. The development was the point.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [
      { label: mirrorfi.name, href: `/projects/${mirrorfi.slug}` },
      { label: "Repository", href: mirrorfi.github },
    ],
    plate: {
      src: "/plates/plate-mirrorfi.jpg",
      caption: "Plate · MirrorFi — the vault wall.",
    },
    figure: MIRRORFI_VAULT,
    plies: [{ from: "g8", to: "f6" }],
    hl: ["g8", "f6"],
    cap: "Position after 4…Nf6",
    puzzle: {
      prompt: "White to move — find the break.",
      target: "d4",
      hit: "d4!! — the annotator agrees.",
      miss: "A developing move. The break was d4.",
    },
  },
  {
    id: "d4",
    type: "mainline",
    parent: "nf6",
    fig: "♙",
    san: "d4",
    moveNumber: 5,
    color: "w",
    sym: "!!",
    label: "The Central Break",
    kind: "Flagship",
    title: "The Central Break",
    fact: `${veridian.name} — ${veridian.subtitle}: intercepts Terraform and Kubernetes and recommends lower-carbon hardware. At Monash: GraphRAG over university regulations, self-correcting Text-to-Cypher, +45% retrieval versus vector-only RAG; an SLM distilled from that reasoning, −50% latency.`,
    commentary:
      "You castle, then you break the centre. d4 is the move this scoresheet hangs on: agents that intercept infrastructure, a graph that actually understands prerequisites, measurements instead of demos. The double-exclaim is Informant’s, not mine — but I played it.",
    eval: 1.6,
    evalText: "!!",
    artifacts: [
      { label: veridian.name, href: `/projects/${veridian.slug}` },
      { label: graphrag.name, href: `/projects/${graphrag.slug}` },
      { label: slm.name, href: `/projects/${slm.slug}` },
    ],
    plate: {
      src: "/plates/plate-veridian.jpg",
      caption: "Plate · Veridian — the central break, intercepted as infrastructure.",
    },
    figure: VERIDIAN_PLANT,
    plies: [{ from: "d2", to: "d4" }],
    hl: ["d2", "d4"],
    cap: "Position after 5. d4",
    inlineDiagram: true,
  },
  {
    id: "closed",
    type: "variation",
    parent: "d4",
    fig: "♟",
    san: "d6",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "The Closed Centre",
    kind: "Project",
    title: "The Closed Centre",
    fact: `${graphrag.name} — ${graphrag.subtitle}. LangGraph over Neo4j and a vector store, self-correcting Text-to-Cypher, +45% retrieval versus vector-only RAG.`,
    commentary:
      "Black can refuse the capture and keep the centre closed. The graph is that kind of patience: prerequisites and credit-transfer as edges, not another embedding dump.",
    eval: 0.55,
    evalText: "+0.55",
    artifacts: [
      { label: graphrag.name, href: `/projects/${graphrag.slug}` },
      { label: "Repository", href: graphrag.github },
    ],
    plate: {
      src: "/plates/plate-graphrag.jpg",
      caption: "Plate · Multi-Agent GraphRAG — the card catalog, not the slogan.",
    },
    plies: [{ from: "d7", to: "d6" }],
    hl: ["d7", "d6"],
    cap: "Position after 5…d6 (Closed Centre)",
  },
  {
    id: "bb6",
    type: "variation",
    parent: "d4",
    fig: "♝",
    san: "Bb6",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "Tucking the Bishop",
    kind: "Project",
    title: "Tucking the Bishop",
    fact: `${slm.name} — ${slm.subtitle}. 70B teacher into a 3B student via QLoRA; DeepSpeed and FlashAttention so the distillation fit; −50% latency, 12× inference.`,
    commentary:
      "The Italian bishop steps back to b6 and still looks at the same diagonal. Distillation is that retreat: a smaller piece, the same job, cheaper to keep on the board.",
    eval: 0.5,
    evalText: "+0.50",
    artifacts: [
      { label: slm.name, href: `/projects/${slm.slug}` },
      { label: "Repository", href: slm.github },
    ],
    plate: {
      src: "/plates/plate-slm.jpg",
      caption: "Plate · SLM Distillation — teacher and student on the same file.",
    },
    plies: [{ from: "c5", to: "b6" }],
    hl: ["c5", "b6"],
    cap: "Position after 5…Bb6 (tucking the bishop)",
  },
  {
    id: "exd4",
    type: "mainline",
    parent: "d4",
    fig: "♟",
    san: "exd4",
    moveNumber: 5,
    color: "b",
    sym: "",
    label: "Taking on d4",
    kind: "Method",
    title: "Taking on d4",
    fact: "Numbers that had to survive the demo: +45% retrieval, −40% oversight, 0.87 AUC, 12× inference on the distilled SLM, 100M events/day.",
    commentary:
      "Accepting the pawn means accepting the tension. I would rather show the graph than the slogan.",
    eval: 0.7,
    evalText: "+0.70",
    artifacts: [{ label: slm.name, href: `/projects/${slm.slug}` }],
    plies: [{ from: "e5", to: "d4" }],
    hl: ["e5", "d4"],
    cap: "Position after 5…exd4",
  },
  {
    id: "re1",
    type: "mainline",
    parent: "exd4",
    fig: "♖",
    san: "Re1",
    moveNumber: 6,
    color: "w",
    sym: "",
    label: "The Open File",
    kind: "Next",
    title: "The Open File",
    fact: `Seeking ${resumeData.targetRoles}`,
    commentary:
      "Rooks belong on open files. This is the current position: sitting on the e-file, waiting for the square where the work already points.",
    eval: 0.8,
    evalText: "+0.80",
    artifacts: [
      { label: "Email", href: mail },
      { label: "GitHub", href: github },
      { label: "LinkedIn", href: linkedin },
      { label: BROADSHEET.printEdition, href: BROADSHEET.printHref },
    ],
    plies: [{ from: "f1", to: "e1" }],
    hl: ["f1", "e1"],
    cap: "Position after 6. Re1",
  },
];
