import type { Claim } from "./types";

export const CLAIMS: readonly Claim[] = [
  { id: "derivCxCost", display: "~80% lower CX cost", type: "production", owner: "Deriv", date: "2026", context: "Full-stack customer-support system that proactively resolves user issues." },
  { id: "derivCsat", display: "CSAT 5/10 → 8/10", type: "production", owner: "Deriv", date: "2026", context: "Average customer satisfaction after the support system shipped." },
  { id: "derivEvents", display: "~20,000 complex events/day", type: "production", owner: "Deriv", date: "2026", context: "Kafka- and API-based ingestion pipelines." },
  { id: "derivTimeToFix", display: "~50% faster time-to-fix", type: "production", owner: "Deriv", date: "2026", context: "Evaluation and debugging harnesses that reproduce production failures." },
  { id: "derivAwsCost", display: "~10–30% lower AWS cost", type: "production", owner: "Deriv", date: "2026", context: "Terraform changes on maintained AWS resources." },
  { id: "derivGoService", display: "4–6 services → one response", type: "capability", owner: "Deriv", date: "2026", context: "Go microservice sized for ~8,000–10,000 requests/day; running in staging, not production." },
  { id: "skribbleErrors", display: "Weekly production errors 16 → 3", type: "production", owner: "Skribble Lab", date: "2026", context: "From high/medium severity to low severity (~80%)." },
  { id: "skribbleMerchants", display: "5+ merchants on Xendit", type: "production", owner: "Skribble Lab", date: "2026", context: "Bank transfer, card and e-wallet payments." },
  { id: "skribbleReach", display: "3,000+ students and parents", type: "production", owner: "Skribble Lab", date: "2026", context: "Onboarding of Chung Ling Private High School (CLPHS)." },
  { id: "monashRetrieval", display: "+45% retrieval vs vector-only", type: "controlled-evaluation", owner: "Monash University contract", date: "2026-02", context: "Self-correcting Text-to-Cypher over a Neo4j graph of university regulations." },
  { id: "slmLatency", display: "−50% inference latency", type: "controlled-evaluation", owner: "Monash University contract", date: "2026-02", context: "Graph-logic SLM distilled on the Monash contract, not the SLM Distillation Engine." },
  { id: "faultlineLocate", display: "First PASS→FAIL commit in 1–5 min", type: "controlled-evaluation", owner: "FaultLine", date: "2026-07", context: "On small-to-medium projects." },
  { id: "faultlineSaved", display: "1–3 h saved per investigation", type: "controlled-evaluation", owner: "FaultLine", date: "2026-07", context: "Compared with manual bisecting." },
  { id: "teleportalTasks", display: "90%+ of demo desktop tasks, unaided", type: "controlled-evaluation", owner: "Gemini Teleportal (with Kai)", date: "2026-03", context: "A demo task set, not general use." },
  { id: "teleportalLatency", display: "~2–5 s from voice to action", type: "controlled-evaluation", owner: "Gemini Teleportal (with Kai)", date: "2026-03", context: "Phone audio and screen video over WebRTC to the Gemini Live API." },
  { id: "circuitmindInspection", display: "Vision and voice PCB inspection", type: "capability", owner: "CircuitMindAI", date: "2026-03", context: "Cached for network loss; detection quality was not measured." },
  { id: "mirrorfiPrize", display: "Grand Prize, Solana Megahack 2025", type: "award", owner: "MirrorFi (team of 6)", date: "2025-05", context: "Out of 150+ teams." },
  { id: "graphragRetrieval", display: "+35% retrieval vs vector-only", type: "controlled-evaluation", owner: "Multi-Agent GraphRAG", date: "2025-10", context: "Independent handbook and policy archive, not the Monash corpus." },
  { id: "setelDefects", display: "−40% production defects", type: "production", owner: "Setel", date: "2025-12", context: "Checkout and capture; a separate observation from the 92.5% coverage." },
  { id: "setelCoverage", display: "92.5% unit-test coverage", type: "controlled-evaluation", owner: "Setel", date: "2025-12", context: "Checkout and capture." },
  { id: "wdOversight", display: "−40% manual oversight", type: "controlled-evaluation", owner: "Western Digital", date: "2025-12", context: "Lab dashboard used by 50+ staff." },
  { id: "leadThroughput", display: "100M-event capacity benchmark", type: "capacity-benchmark", owner: "Distributed Lead Scorer", date: "2025-05", context: "Pipeline capacity, not sustained traffic." },
  { id: "veridianUptime", display: "99.9% observed uptime", type: "controlled-evaluation", owner: "Veridian", date: "2026-04", context: "Cloud Run evaluation, not a production SLO." },
  { id: "veridianEmissions", display: "−15% cloud emissions", type: "controlled-evaluation", owner: "Veridian", date: "2026-04", context: "Against the default unscheduled Cloud Run service." },
  { id: "riskAuc", display: "0.87 AUC-ROC", type: "controlled-evaluation", owner: "Financial Risk Predictor", date: "2025-07", context: "Offline evaluation, no published comparator." },
  { id: "slmInference", display: "70B → 3B student", type: "controlled-evaluation", owner: "SLM Distillation Engine", date: "2025-07", context: "No speed-up claimed." },
  { id: "gateC", display: "−143 Elo @ 50k nodes", type: "controlled-benchmark", owner: "Chess engine lab", date: "2026-09-03", context: "128 games against handcrafted PeSTO; SPRT terminated for H0." },
];
