import type { Project, ProjectCategory } from "./types";

export const CATEGORY_LABEL: Record<ProjectCategory, string> = {
  ml: "ML / data systems",
  product: "Product / backend",
  devtools: "Developer tools",
};

export const FEATURED_SLUGS = ["faultline", "gemini-teleportal", "circuitmindai"] as const;

export const PROJECTS: readonly Project[] = [
  {
    slug: "faultline",
    name: "FaultLine",
    subtitle: "Regression and leak-evidence CLI",
    date: "2026-07",
    origin: "Solo",
    category: "devtools",
    group: "featured",
    repo: "https://github.com/Mizore66/faultline",
    tech: ["Go", "Docker", "GitHub Actions", "Sigstore"],
    purpose: "Replays a frozen, human-reviewed check across Git history in Docker sandboxes to find the first reliable PASS→FAIL commit.",
    result: { claimId: "faultlineLocate", line: "First PASS→FAIL commit in 1–5 min" },
    seo: {
      title: "FaultLine — Regression and leak-evidence CLI",
      description: "A Go CLI that replays a frozen, human-reviewed check across Git history in Docker sandboxes to find the first reliable PASS→FAIL commit.",
    },
  },
  {
    slug: "gemini-teleportal",
    name: "Gemini Teleportal",
    subtitle: "Voice-controlled desktop AI agent",
    date: "2026-03",
    origin: "Built with Kai",
    category: "product",
    group: "featured",
    repo: "https://github.com/Kaiz404/Teleportal",
    tech: ["Next.js", "TypeScript", "Python", "Gemini Live API", "WebRTC", "Firebase", "Cloud Run"],
    purpose: "Streams phone audio and screen video to the Gemini Live API, which drives the Windows desktop by exact UI element ids.",
    result: { claimId: "teleportalTasks", line: "90%+ of demo desktop tasks, unaided" },
    seo: {
      title: "Gemini Teleportal — Voice-controlled desktop AI agent",
      description: "A voice-controlled desktop agent built with Kai: phone audio and screen video stream over WebRTC to the Gemini Live API, which drives the Windows UI.",
    },
  },
  {
    slug: "circuitmindai",
    name: "CircuitMindAI",
    subtitle: "PCB inspection",
    date: "2026-03",
    origin: "Solo",
    category: "product",
    group: "featured",
    repo: "https://github.com/Mizore66/CircuitMindAI",
    tech: ["Next.js", "Amazon Bedrock", "Express", "OpenSearch Serverless", "GitHub Actions", "ECS Fargate"],
    purpose: "Images in, voice-guided inspection steps out, with cached results for network loss.",
    result: { claimId: "circuitmindInspection", line: "Vision and voice PCB inspection" },
    seo: {
      title: "CircuitMindAI — PCB inspection",
      description: "Nova Pro analyses the PCB image; Nova Sonic talks the operator through the fault. Next.js and Express on ECS Fargate.",
    },
  },
  {
    slug: "veridian",
    name: "Veridian",
    subtitle: "MLOps tradeoff engine",
    date: "2026-04",
    origin: "Solo",
    category: "ml",
    group: "archive",
    tech: ["Python", "Terraform", "BigQuery", "GCP Vertex AI", "GitLab Duo", "MCP"],
    purpose: "Intercepts Terraform and Kubernetes and recommends a lower-carbon compute configuration before provisioning or a demand-driven scale event.",
    result: { claimId: "veridianEmissions", line: "−15% cloud emissions (Cloud Run evaluation)" },
    seo: {
      title: "Veridian — MLOps tradeoff engine",
      description: "GitLab Duo intercepts Terraform; Vertex AI recommends a lower-carbon compute configuration; BigQuery keeps the carbon ledger off the request.",
    },
  },
  {
    slug: "multi-agent-graphrag",
    name: "Multi-Agent GraphRAG",
    subtitle: "Policy-corpus retrieval",
    date: "2025-10",
    origin: "Solo",
    category: "ml",
    group: "archive",
    tech: ["LangGraph", "Neo4j", "Vector DB", "Knowledge Graphs", "RAG"],
    purpose: "LangGraph over an independent university handbook and policy archive, with a vector fallback.",
    result: { claimId: "graphragRetrieval", line: "+35% retrieval vs vector-only" },
    seo: {
      title: "Multi-Agent GraphRAG — Policy-corpus retrieval",
      description: "LangGraph over an independent university handbook and policy archive: agents write Cypher, check it, and fall back to a vector store. +35% retrieval.",
    },
  },
  {
    slug: "mirrorfi",
    name: "MirrorFi",
    subtitle: "Solana vault strategy platform",
    date: "2025-05",
    origin: "Hackathon team of 6",
    category: "product",
    group: "archive",
    repo: "https://github.com/Mizore66/MirrorFi",
    tech: ["Next.js", "ShadCN", "MongoDB", "Solana", "Node.js"],
    purpose: "A no-code builder for sharing and executing Solana yield strategies across Drift, Jupiter and Meteora.",
    result: { claimId: "mirrorfiPrize", line: "Grand Prize, Solana Megahack 2025" },
    seo: {
      title: "MirrorFi — Solana vault strategy platform",
      description: "Grand Prize, Solana Megahack 2025: a no-code builder for sharing and executing Solana yield strategies across Drift, Jupiter and Meteora.",
    },
  },
  {
    slug: "financial-risk-predictor",
    name: "Financial Risk Predictor",
    subtitle: "ML risk assessment",
    date: "2025-07",
    origin: "Solo",
    category: "ml",
    group: "archive",
    tech: ["TensorFlow", "XGBoost", "LightGBM", "BentoML", "SHAP", "Kafka"],
    purpose: "Daily credit-risk scores that have to be interpreted, served, and retrained.",
    result: { claimId: "riskAuc", line: "0.87 AUC-ROC" },
    seo: {
      title: "Financial Risk Predictor — ML risk assessment",
      description: "Kafka feeds the daily tape. LightGBM and XGBoost score it at 0.87 AUC-ROC. SHAP writes why. BentoML serves the number.",
    },
  },
  {
    slug: "distributed-lead-scorer",
    name: "Distributed Lead Scorer",
    subtitle: "Large-scale data mining pipeline",
    date: "2025-05",
    origin: "Solo",
    category: "ml",
    group: "archive",
    tech: ["PySpark", "PyTorch DDP", "Deep Interest Network"],
    purpose: "Scores conversion on a hundred million events a day, with checkpoints so a failed hour can resume.",
    result: { claimId: "leadThroughput", line: "100M-event capacity benchmark" },
    seo: {
      title: "Distributed Lead Scorer — Large-scale data mining pipeline",
      description: "Capacity-benchmarked at 100M events/day. A Deep Interest Network on PyTorch DDP scores conversion. Checkpoints resume from the last completed slice.",
    },
  },
  {
    slug: "slm-distillation-engine",
    name: "SLM Distillation Engine",
    subtitle: "Knowledge distillation and fine-tuning",
    date: "2025-07",
    origin: "Lab experiment",
    category: "ml",
    group: "lab",
    tech: ["PyTorch", "QLoRA", "DeepSpeed", "FlashAttention"],
    purpose: "A 70B teacher distilled into a 3B student with QLoRA, DeepSpeed and FlashAttention.",
    result: { claimId: "slmInference", line: "70B → 3B student" },
    seo: {
      title: "SLM Distillation Engine — Knowledge distillation and fine-tuning",
      description: "A 70B teacher writes the traces; QLoRA, DeepSpeed and FlashAttention compress them into a 3B student. No speed-up claimed.",
    },
  },
];
